--
-- PostgreSQL database dump
--

\restrict kOPeEK4bWobu9iJQy2bqqMMckbH8Uc27snCVGBcFvrOekWp09LdhTCs15D1dJfx

-- Dumped from database version 14.23 (Ubuntu 14.23-0ubuntu0.22.04.1)
-- Dumped by pg_dump version 14.23 (Ubuntu 14.23-0ubuntu0.22.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: contract; Type: TABLE; Schema: public; Owner: p1mps
--

CREATE TABLE public.contract (
    id integer NOT NULL,
    is_opposing boolean NOT NULL,
    type character varying(50) NOT NULL,
    employer character varying(255) NOT NULL,
    employer_affiliation character varying(255) NOT NULL,
    scale integer NOT NULL,
    duration_months integer NOT NULL,
    base_pay_percent integer,
    command_rights character varying(50) NOT NULL,
    support_terms character varying(255) NOT NULL,
    salvage_rights character varying(255) NOT NULL,
    transport_terms character varying(255) NOT NULL,
    number_of_tracks integer NOT NULL,
    tracks_completed integer NOT NULL,
    status character varying(50) NOT NULL,
    created_at timestamp(0) without time zone NOT NULL,
    accepted_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    company_id integer,
    opposing_company_id integer,
    linked_contract_id integer,
    planet character varying(255) DEFAULT NULL::character varying,
    intensity character varying(255) DEFAULT NULL::character varying,
    name character varying(255) DEFAULT NULL::character varying
);


ALTER TABLE public.contract OWNER TO p1mps;

--
-- Name: contract_id_seq; Type: SEQUENCE; Schema: public; Owner: p1mps
--

ALTER TABLE public.contract ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contract_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: contract_log_entry; Type: TABLE; Schema: public; Owner: p1mps
--

CREATE TABLE public.contract_log_entry (
    id integer NOT NULL,
    month integer NOT NULL,
    entry_type character varying(50) NOT NULL,
    description text NOT NULL,
    roll_result integer,
    data json,
    created_at timestamp(0) without time zone NOT NULL,
    contract_id integer NOT NULL,
    track_id integer,
    support_point_entry_id integer
);


ALTER TABLE public.contract_log_entry OWNER TO p1mps;

--
-- Name: contract_log_entry_id_seq; Type: SEQUENCE; Schema: public; Owner: p1mps
--

ALTER TABLE public.contract_log_entry ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contract_log_entry_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: doctrine_migration_versions; Type: TABLE; Schema: public; Owner: p1mps
--

CREATE TABLE public.doctrine_migration_versions (
    version character varying(191) NOT NULL,
    executed_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    execution_time integer
);


ALTER TABLE public.doctrine_migration_versions OWNER TO p1mps;

--
-- Name: mercenary_company; Type: TABLE; Schema: public; Owner: p1mps
--

CREATE TABLE public.mercenary_company (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    faction character varying(255) NOT NULL,
    reputation integer NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.mercenary_company OWNER TO p1mps;

--
-- Name: mercenary_company_id_seq; Type: SEQUENCE; Schema: public; Owner: p1mps
--

ALTER TABLE public.mercenary_company ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mercenary_company_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: messenger_messages; Type: TABLE; Schema: public; Owner: p1mps
--

CREATE TABLE public.messenger_messages (
    id bigint NOT NULL,
    body text NOT NULL,
    headers text NOT NULL,
    queue_name character varying(190) NOT NULL,
    created_at timestamp(0) without time zone NOT NULL,
    available_at timestamp(0) without time zone NOT NULL,
    delivered_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone
);


ALTER TABLE public.messenger_messages OWNER TO p1mps;

--
-- Name: messenger_messages_id_seq; Type: SEQUENCE; Schema: public; Owner: p1mps
--

ALTER TABLE public.messenger_messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.messenger_messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pilot; Type: TABLE; Schema: public; Owner: p1mps
--

CREATE TABLE public.pilot (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    is_named boolean NOT NULL,
    gunnery integer NOT NULL,
    piloting integer NOT NULL,
    xp integer NOT NULL,
    company_id integer NOT NULL
);


ALTER TABLE public.pilot OWNER TO p1mps;

--
-- Name: pilot_id_seq; Type: SEQUENCE; Schema: public; Owner: p1mps
--

ALTER TABLE public.pilot ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pilot_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: support_point_entry; Type: TABLE; Schema: public; Owner: p1mps
--

CREATE TABLE public.support_point_entry (
    id integer NOT NULL,
    amount integer NOT NULL,
    description character varying(255) NOT NULL,
    created_at timestamp(0) without time zone NOT NULL,
    company_id integer NOT NULL
);


ALTER TABLE public.support_point_entry OWNER TO p1mps;

--
-- Name: support_point_entry_id_seq; Type: SEQUENCE; Schema: public; Owner: p1mps
--

ALTER TABLE public.support_point_entry ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.support_point_entry_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: track_record; Type: TABLE; Schema: public; Owner: p1mps
--

CREATE TABLE public.track_record (
    id integer NOT NULL,
    track_number integer NOT NULL,
    mission_type character varying(255) NOT NULL,
    terrain character varying(255) NOT NULL,
    command_complication text,
    combat_pay_tier character varying(50) DEFAULT NULL::character varying,
    status character varying(50) NOT NULL,
    created_at timestamp(0) without time zone NOT NULL,
    completed_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    contract_id integer NOT NULL,
    taking_one_for_team boolean NOT NULL
);


ALTER TABLE public.track_record OWNER TO p1mps;

--
-- Name: track_record_id_seq; Type: SEQUENCE; Schema: public; Owner: p1mps
--

ALTER TABLE public.track_record ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.track_record_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: unit; Type: TABLE; Schema: public; Owner: p1mps
--

CREATE TABLE public.unit (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    chassis character varying(255) NOT NULL,
    tonnage integer NOT NULL,
    bv integer NOT NULL,
    unit_type character varying(50) NOT NULL,
    damage_state character varying(50) NOT NULL,
    is_active boolean NOT NULL,
    company_id integer NOT NULL,
    pilot_id integer
);


ALTER TABLE public.unit OWNER TO p1mps;

--
-- Name: unit_id_seq; Type: SEQUENCE; Schema: public; Owner: p1mps
--

ALTER TABLE public.unit ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.unit_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user; Type: TABLE; Schema: public; Owner: p1mps
--

CREATE TABLE public."user" (
    id integer NOT NULL,
    username character varying(180) NOT NULL,
    email character varying(255) NOT NULL,
    password character varying(255) NOT NULL
);


ALTER TABLE public."user" OWNER TO p1mps;

--
-- Name: user_id_seq; Type: SEQUENCE; Schema: public; Owner: p1mps
--

ALTER TABLE public."user" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: contract; Type: TABLE DATA; Schema: public; Owner: p1mps
--

COPY public.contract (id, is_opposing, type, employer, employer_affiliation, scale, duration_months, base_pay_percent, command_rights, support_terms, salvage_rights, transport_terms, number_of_tracks, tracks_completed, status, created_at, accepted_at, company_id, opposing_company_id, linked_contract_id, planet, intensity, name) FROM stdin;
6	f	garrison	Noble (Local)	Star league	1	3	100	independent	0%	60%	100%	2	0	active	2026-06-27 09:44:37	2026-06-27 09:44:37	1	\N	\N	Somerset	0-1-1	Act of piracy contract
2	f	raid	Corporation	Lyran Commonwealth	1	3	110	liaison	Straight/100%	10%	50%	2	0	active	2026-06-26 09:49:50	2026-06-26 09:49:50	3	2	\N	Sommerset	0-0-2	Sommerset Steal the treasure (raider)
4	f	garrison	Noble (Local)	Lyran Commonwealth	1	3	100	house	Straight/60%	30%	100%	2	1	active	2026-06-27 09:40:45	2026-06-27 09:40:45	2	2	\N	Sommerset	0-0-2	Sommerset Defender Contract
\.


--
-- Data for Name: contract_log_entry; Type: TABLE DATA; Schema: public; Owner: p1mps
--

COPY public.contract_log_entry (id, month, entry_type, description, roll_result, data, created_at, contract_id, track_id, support_point_entry_id) FROM stdin;
71	1	transport	Transport: 50 + (50 × 2) = 150 SP total — employer covers 100% (+150 SP) → player pays -0 SP	\N	\N	2026-06-27 23:57:56	4	\N	53
73	1	maintenance	Maintenance deducted: -500 SP	\N	\N	2026-06-27 23:58:23	4	\N	55
75	1	base_pay	Base pay received: +500 SP	\N	\N	2026-06-27 23:59:08	4	\N	57
80	2	maintenance	Maintenance deducted: -500 SP	\N	\N	2026-06-27 23:59:55	4	\N	60
81	2	base_pay	Base pay received: +500 SP	\N	\N	2026-06-27 23:59:58	4	\N	61
82	3	maintenance	Maintenance deducted: -500 SP	\N	\N	2026-06-28 00:00:05	4	\N	62
83	3	base_pay	Base pay received: +500 SP	\N	\N	2026-06-28 00:00:09	4	\N	63
87	3	track_setup	Track 1: Secure on Hills (MegaMek: Hills-pastoral)	\N	{"missionType":"Secure","missionRoll":2,"terrain":"Hills","terrainSetting":"Hills-pastoral","terrainRoll":5,"complication":"Landslide risk. Any unit that moves through level 3+ terrain must make a PSR.","complicationRoll":8}	2026-06-28 00:04:46	4	6	\N
89	3	post_track	Combat pay: none (none). No salvage.	\N	\N	2026-06-28 00:34:00	4	\N	\N
90	3	track_setup	Track 2: Secure on Wooded (MegaMek: Wooded-hills)	\N	{"missionType":"Secure","missionRoll":3,"terrain":"Wooded","terrainSetting":"Wooded-hills","terrainRoll":6,"complication":"Logging obstructions. 1d6 hexes of clear terrain become light woods.","complicationRoll":8}	2026-06-28 00:35:01	4	7	\N
\.


--
-- Data for Name: doctrine_migration_versions; Type: TABLE DATA; Schema: public; Owner: p1mps
--

COPY public.doctrine_migration_versions (version, executed_at, execution_time) FROM stdin;
DoctrineMigrations\\Version20260624121344	2026-06-25 11:52:05	239
DoctrineMigrations\\Version20260624134538	2026-06-25 11:52:05	2
DoctrineMigrations\\Version20260624165605	2026-06-25 11:52:05	2
DoctrineMigrations\\Version20260626204505	2026-06-26 20:46:45	7
DoctrineMigrations\\Version20260628015000	2026-06-27 23:55:25	51
\.


--
-- Data for Name: mercenary_company; Type: TABLE DATA; Schema: public; Owner: p1mps
--

COPY public.mercenary_company (id, name, faction, reputation, user_id) FROM stdin;
1	Mitchell's Mongrels	Mercenary	1	1
2	The scavengers 1st force	Raven alliance	1	2
3	Peregrine's Outcast	Jade Falcon	1	3
\.


--
-- Data for Name: messenger_messages; Type: TABLE DATA; Schema: public; Owner: p1mps
--

COPY public.messenger_messages (id, body, headers, queue_name, created_at, available_at, delivered_at) FROM stdin;
\.


--
-- Data for Name: pilot; Type: TABLE DATA; Schema: public; Owner: p1mps
--

COPY public.pilot (id, name, is_named, gunnery, piloting, xp, company_id) FROM stdin;
1	Pitch Black	t	4	5	0	2
2	Scrappy	t	4	5	0	2
\.


--
-- Data for Name: support_point_entry; Type: TABLE DATA; Schema: public; Owner: p1mps
--

COPY public.support_point_entry (id, amount, description, created_at, company_id) FROM stdin;
60	-500	Contract maintenance (scale 1)	2026-06-27 23:59:55	2
61	500	Base pay (scale 1)	2026-06-27 23:59:58	2
62	-500	Contract maintenance (scale 1)	2026-06-28 00:00:05	2
63	500	Base pay (scale 1)	2026-06-28 00:00:09	2
52	3000	Starting points	2026-06-27 23:57:45	2
53	0	Transport (2 jumps)	2026-06-27 23:57:56	2
55	-500	Contract maintenance (scale 1)	2026-06-27 23:58:23	2
57	500	Base pay (scale 1)	2026-06-27 23:59:08	2
\.


--
-- Data for Name: track_record; Type: TABLE DATA; Schema: public; Owner: p1mps
--

COPY public.track_record (id, track_number, mission_type, terrain, command_complication, combat_pay_tier, status, created_at, completed_at, contract_id, taking_one_for_team) FROM stdin;
1	1	Reconnaissance	Desert	No Complication	none	completed	2026-06-27 14:03:44	2026-06-27 14:05:51	4	f
2	1	Secure	Desert	Sandstorm. All DE and P weapons suffer +1 to hit this track.	none	completed	2026-06-27 22:09:40	2026-06-27 22:09:46	4	f
3	1	Calamity	Wooded	Concealed defenders. Opponent may deploy all units as hidden.	none	completed	2026-06-27 23:27:20	2026-06-27 23:27:32	4	f
4	1	Duel	Hills	Rough terrain. All ground units movement reduced by 1 MP this track.	none	completed	2026-06-27 23:59:25	2026-06-27 23:59:33	4	f
5	1	Reconnaissance	Hills	No Complication	none	completed	2026-06-28 00:00:14	2026-06-28 00:00:19	4	f
6	1	Secure	Hills	Landslide risk. Any unit that moves through level 3+ terrain must make a PSR.	none	completed	2026-06-28 00:04:46	2026-06-28 00:34:00	4	f
7	2	Secure	Wooded	Logging obstructions. 1d6 hexes of clear terrain become light woods.	\N	pending	2026-06-28 00:35:01	\N	4	f
\.


--
-- Data for Name: unit; Type: TABLE DATA; Schema: public; Owner: p1mps
--

COPY public.unit (id, name, chassis, tonnage, bv, unit_type, damage_state, is_active, company_id, pilot_id) FROM stdin;
1	Event Horizon	Black Hawk (Nova) S	50	2056	mech	none	t	2	1
2	Distant Thunder	Whitworth WTH-2	40	936	mech	none	t	2	2
\.


--
-- Data for Name: user; Type: TABLE DATA; Schema: public; Owner: p1mps
--

COPY public."user" (id, username, email, password) FROM stdin;
1	MitchellWelsh	mitchellcwelsh@outlook.com	$2y$13$UCLE0vXuNBq.ZIM.BpjO6.2mXFlf4pjXEchL0ifG4Q.p0hXbpQ4u2
2	Andrea	imparato.andrea@gmail.com	$2y$13$3894MxDJgJy4B25Wulz5uOXAGeW.qJA1q6CYxIF0BOPDDjf2LoMVq
3	Zidahya	zidahya@gmx.net	$2y$13$Ht91GVH2WJqw16ELCR2zLe/QXlnyh61HBCuzRzL.1OISd7LfNdcLW
\.


--
-- Name: contract_id_seq; Type: SEQUENCE SET; Schema: public; Owner: p1mps
--

SELECT pg_catalog.setval('public.contract_id_seq', 6, true);


--
-- Name: contract_log_entry_id_seq; Type: SEQUENCE SET; Schema: public; Owner: p1mps
--

SELECT pg_catalog.setval('public.contract_log_entry_id_seq', 90, true);


--
-- Name: mercenary_company_id_seq; Type: SEQUENCE SET; Schema: public; Owner: p1mps
--

SELECT pg_catalog.setval('public.mercenary_company_id_seq', 3, true);


--
-- Name: messenger_messages_id_seq; Type: SEQUENCE SET; Schema: public; Owner: p1mps
--

SELECT pg_catalog.setval('public.messenger_messages_id_seq', 1, false);


--
-- Name: pilot_id_seq; Type: SEQUENCE SET; Schema: public; Owner: p1mps
--

SELECT pg_catalog.setval('public.pilot_id_seq', 2, true);


--
-- Name: support_point_entry_id_seq; Type: SEQUENCE SET; Schema: public; Owner: p1mps
--

SELECT pg_catalog.setval('public.support_point_entry_id_seq', 63, true);


--
-- Name: track_record_id_seq; Type: SEQUENCE SET; Schema: public; Owner: p1mps
--

SELECT pg_catalog.setval('public.track_record_id_seq', 7, true);


--
-- Name: unit_id_seq; Type: SEQUENCE SET; Schema: public; Owner: p1mps
--

SELECT pg_catalog.setval('public.unit_id_seq', 2, true);


--
-- Name: user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: p1mps
--

SELECT pg_catalog.setval('public.user_id_seq', 3, true);


--
-- Name: contract_log_entry contract_log_entry_pkey; Type: CONSTRAINT; Schema: public; Owner: p1mps
--

ALTER TABLE ONLY public.contract_log_entry
    ADD CONSTRAINT contract_log_entry_pkey PRIMARY KEY (id);


--
-- Name: contract contract_pkey; Type: CONSTRAINT; Schema: public; Owner: p1mps
--

ALTER TABLE ONLY public.contract
    ADD CONSTRAINT contract_pkey PRIMARY KEY (id);


--
-- Name: doctrine_migration_versions doctrine_migration_versions_pkey; Type: CONSTRAINT; Schema: public; Owner: p1mps
--

ALTER TABLE ONLY public.doctrine_migration_versions
    ADD CONSTRAINT doctrine_migration_versions_pkey PRIMARY KEY (version);


--
-- Name: mercenary_company mercenary_company_pkey; Type: CONSTRAINT; Schema: public; Owner: p1mps
--

ALTER TABLE ONLY public.mercenary_company
    ADD CONSTRAINT mercenary_company_pkey PRIMARY KEY (id);


--
-- Name: messenger_messages messenger_messages_pkey; Type: CONSTRAINT; Schema: public; Owner: p1mps
--

ALTER TABLE ONLY public.messenger_messages
    ADD CONSTRAINT messenger_messages_pkey PRIMARY KEY (id);


--
-- Name: pilot pilot_pkey; Type: CONSTRAINT; Schema: public; Owner: p1mps
--

ALTER TABLE ONLY public.pilot
    ADD CONSTRAINT pilot_pkey PRIMARY KEY (id);


--
-- Name: support_point_entry support_point_entry_pkey; Type: CONSTRAINT; Schema: public; Owner: p1mps
--

ALTER TABLE ONLY public.support_point_entry
    ADD CONSTRAINT support_point_entry_pkey PRIMARY KEY (id);


--
-- Name: track_record track_record_pkey; Type: CONSTRAINT; Schema: public; Owner: p1mps
--

ALTER TABLE ONLY public.track_record
    ADD CONSTRAINT track_record_pkey PRIMARY KEY (id);


--
-- Name: unit unit_pkey; Type: CONSTRAINT; Schema: public; Owner: p1mps
--

ALTER TABLE ONLY public.unit
    ADD CONSTRAINT unit_pkey PRIMARY KEY (id);


--
-- Name: user user_pkey; Type: CONSTRAINT; Schema: public; Owner: p1mps
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT user_pkey PRIMARY KEY (id);


--
-- Name: idx_26c82ebb2576e0fd; Type: INDEX; Schema: public; Owner: p1mps
--

CREATE INDEX idx_26c82ebb2576e0fd ON public.contract_log_entry USING btree (contract_id);


--
-- Name: idx_26c82ebb5ed23c43; Type: INDEX; Schema: public; Owner: p1mps
--

CREATE INDEX idx_26c82ebb5ed23c43 ON public.contract_log_entry USING btree (track_id);


--
-- Name: idx_5d56e8c3979b1ad6; Type: INDEX; Schema: public; Owner: p1mps
--

CREATE INDEX idx_5d56e8c3979b1ad6 ON public.support_point_entry USING btree (company_id);


--
-- Name: idx_75ea56e0fb7336f0e3bd61ce16ba31dbbf396750; Type: INDEX; Schema: public; Owner: p1mps
--

CREATE INDEX idx_75ea56e0fb7336f0e3bd61ce16ba31dbbf396750 ON public.messenger_messages USING btree (queue_name, available_at, delivered_at, id);


--
-- Name: idx_8d1e5f52979b1ad6; Type: INDEX; Schema: public; Owner: p1mps
--

CREATE INDEX idx_8d1e5f52979b1ad6 ON public.pilot USING btree (company_id);


--
-- Name: idx_d3f65e782576e0fd; Type: INDEX; Schema: public; Owner: p1mps
--

CREATE INDEX idx_d3f65e782576e0fd ON public.track_record USING btree (contract_id);


--
-- Name: idx_dcbb0c53979b1ad6; Type: INDEX; Schema: public; Owner: p1mps
--

CREATE INDEX idx_dcbb0c53979b1ad6 ON public.unit USING btree (company_id);


--
-- Name: idx_e98f2859979b1ad6; Type: INDEX; Schema: public; Owner: p1mps
--

CREATE INDEX idx_e98f2859979b1ad6 ON public.contract USING btree (company_id);


--
-- Name: idx_e98f2859ea4ebd8c; Type: INDEX; Schema: public; Owner: p1mps
--

CREATE INDEX idx_e98f2859ea4ebd8c ON public.contract USING btree (opposing_company_id);


--
-- Name: uniq_6461c2ca76ed395; Type: INDEX; Schema: public; Owner: p1mps
--

CREATE UNIQUE INDEX uniq_6461c2ca76ed395 ON public.mercenary_company USING btree (user_id);


--
-- Name: uniq_70799797a7b9b420; Type: INDEX; Schema: public; Owner: p1mps
--

CREATE UNIQUE INDEX uniq_70799797a7b9b420 ON public.contract_log_entry USING btree (support_point_entry_id);


--
-- Name: uniq_8d93d649e7927c74; Type: INDEX; Schema: public; Owner: p1mps
--

CREATE UNIQUE INDEX uniq_8d93d649e7927c74 ON public."user" USING btree (email);


--
-- Name: uniq_8d93d649f85e0677; Type: INDEX; Schema: public; Owner: p1mps
--

CREATE UNIQUE INDEX uniq_8d93d649f85e0677 ON public."user" USING btree (username);


--
-- Name: uniq_dcbb0c53ce55439b; Type: INDEX; Schema: public; Owner: p1mps
--

CREATE UNIQUE INDEX uniq_dcbb0c53ce55439b ON public.unit USING btree (pilot_id);


--
-- Name: uniq_e98f2859cd59f015; Type: INDEX; Schema: public; Owner: p1mps
--

CREATE UNIQUE INDEX uniq_e98f2859cd59f015 ON public.contract USING btree (linked_contract_id);


--
-- Name: contract_log_entry fk_26c82ebb2576e0fd; Type: FK CONSTRAINT; Schema: public; Owner: p1mps
--

ALTER TABLE ONLY public.contract_log_entry
    ADD CONSTRAINT fk_26c82ebb2576e0fd FOREIGN KEY (contract_id) REFERENCES public.contract(id);


--
-- Name: contract_log_entry fk_26c82ebb5ed23c43; Type: FK CONSTRAINT; Schema: public; Owner: p1mps
--

ALTER TABLE ONLY public.contract_log_entry
    ADD CONSTRAINT fk_26c82ebb5ed23c43 FOREIGN KEY (track_id) REFERENCES public.track_record(id);


--
-- Name: support_point_entry fk_5d56e8c3979b1ad6; Type: FK CONSTRAINT; Schema: public; Owner: p1mps
--

ALTER TABLE ONLY public.support_point_entry
    ADD CONSTRAINT fk_5d56e8c3979b1ad6 FOREIGN KEY (company_id) REFERENCES public.mercenary_company(id);


--
-- Name: mercenary_company fk_6461c2ca76ed395; Type: FK CONSTRAINT; Schema: public; Owner: p1mps
--

ALTER TABLE ONLY public.mercenary_company
    ADD CONSTRAINT fk_6461c2ca76ed395 FOREIGN KEY (user_id) REFERENCES public."user"(id);


--
-- Name: contract_log_entry fk_70799797a7b9b420; Type: FK CONSTRAINT; Schema: public; Owner: p1mps
--

ALTER TABLE ONLY public.contract_log_entry
    ADD CONSTRAINT fk_70799797a7b9b420 FOREIGN KEY (support_point_entry_id) REFERENCES public.support_point_entry(id) ON DELETE SET NULL;


--
-- Name: pilot fk_8d1e5f52979b1ad6; Type: FK CONSTRAINT; Schema: public; Owner: p1mps
--

ALTER TABLE ONLY public.pilot
    ADD CONSTRAINT fk_8d1e5f52979b1ad6 FOREIGN KEY (company_id) REFERENCES public.mercenary_company(id);


--
-- Name: track_record fk_d3f65e782576e0fd; Type: FK CONSTRAINT; Schema: public; Owner: p1mps
--

ALTER TABLE ONLY public.track_record
    ADD CONSTRAINT fk_d3f65e782576e0fd FOREIGN KEY (contract_id) REFERENCES public.contract(id);


--
-- Name: unit fk_dcbb0c53979b1ad6; Type: FK CONSTRAINT; Schema: public; Owner: p1mps
--

ALTER TABLE ONLY public.unit
    ADD CONSTRAINT fk_dcbb0c53979b1ad6 FOREIGN KEY (company_id) REFERENCES public.mercenary_company(id);


--
-- Name: unit fk_dcbb0c53ce55439b; Type: FK CONSTRAINT; Schema: public; Owner: p1mps
--

ALTER TABLE ONLY public.unit
    ADD CONSTRAINT fk_dcbb0c53ce55439b FOREIGN KEY (pilot_id) REFERENCES public.pilot(id);


--
-- Name: contract fk_e98f2859979b1ad6; Type: FK CONSTRAINT; Schema: public; Owner: p1mps
--

ALTER TABLE ONLY public.contract
    ADD CONSTRAINT fk_e98f2859979b1ad6 FOREIGN KEY (company_id) REFERENCES public.mercenary_company(id);


--
-- Name: contract fk_e98f2859cd59f015; Type: FK CONSTRAINT; Schema: public; Owner: p1mps
--

ALTER TABLE ONLY public.contract
    ADD CONSTRAINT fk_e98f2859cd59f015 FOREIGN KEY (linked_contract_id) REFERENCES public.contract(id);


--
-- Name: contract fk_e98f2859ea4ebd8c; Type: FK CONSTRAINT; Schema: public; Owner: p1mps
--

ALTER TABLE ONLY public.contract
    ADD CONSTRAINT fk_e98f2859ea4ebd8c FOREIGN KEY (opposing_company_id) REFERENCES public.mercenary_company(id);


--
-- PostgreSQL database dump complete
--

\unrestrict kOPeEK4bWobu9iJQy2bqqMMckbH8Uc27snCVGBcFvrOekWp09LdhTCs15D1dJfx

