--
-- PostgreSQL database dump
--

\restrict QstsbnGqyyt9IYY3gUx8PlEf8v6KhiuKcw469rQfWxHGQZt7pmR0uOJRTYy39JH

-- Dumped from database version 14.23 (Ubuntu 14.23-0ubuntu0.22.04.1)
-- Dumped by pg_dump version 14.23 (Ubuntu 14.23-0ubuntu0.22.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: contract; Type: TABLE; Schema: public; Owner: p1mps
--

CREATE TABLE public.contract (
    id integer NOT NULL,
    is_opposing boolean NOT NULL,
    type character varying(50) NOT NULL,
    employer character varying(255) NOT NULL,
    employer_affiliation character varying(255) NOT NULL,
    scale integer NOT NULL,
    duration_months integer NOT NULL,
    base_pay_percent integer,
    command_rights character varying(50) NOT NULL,
    support_terms character varying(255) NOT NULL,
    salvage_rights character varying(255) NOT NULL,
    transport_terms character varying(255) NOT NULL,
    number_of_tracks integer NOT NULL,
    tracks_completed integer NOT NULL,
    status character varying(50) NOT NULL,
    created_at timestamp(0) without time zone NOT NULL,
    accepted_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    company_id integer,
    opposing_company_id integer,
    linked_contract_id integer,
    planet character varying(255) DEFAULT NULL::character varying,
    intensity character varying(255) DEFAULT NULL::character varying,
    name character varying(255) DEFAULT NULL::character varying,
    description text
);


ALTER TABLE public.contract OWNER TO p1mps;

--
-- Name: contract_id_seq; Type: SEQUENCE; Schema: public; Owner: p1mps
--

ALTER TABLE public.contract ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contract_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: contract_log_entry; Type: TABLE; Schema: public; Owner: p1mps
--

CREATE TABLE public.contract_log_entry (
    id integer NOT NULL,
    month integer NOT NULL,
    entry_type character varying(50) NOT NULL,
    description text NOT NULL,
    roll_result integer,
    data json,
    created_at timestamp(0) without time zone NOT NULL,
    contract_id integer NOT NULL,
    track_id integer,
    support_point_entry_id integer
);


ALTER TABLE public.contract_log_entry OWNER TO p1mps;

--
-- Name: contract_log_entry_id_seq; Type: SEQUENCE; Schema: public; Owner: p1mps
--

ALTER TABLE public.contract_log_entry ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contract_log_entry_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: doctrine_migration_versions; Type: TABLE; Schema: public; Owner: p1mps
--

CREATE TABLE public.doctrine_migration_versions (
    version character varying(191) NOT NULL,
    executed_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    execution_time integer
);


ALTER TABLE public.doctrine_migration_versions OWNER TO p1mps;

--
-- Name: dropship; Type: TABLE; Schema: public; Owner: p1mps
--

CREATE TABLE public.dropship (
    id integer NOT NULL,
    max_capacity integer NOT NULL,
    company_id integer NOT NULL,
    name character varying(255) DEFAULT NULL::character varying,
    mekbay_capacity integer NOT NULL
);


ALTER TABLE public.dropship OWNER TO p1mps;

--
-- Name: dropship_id_seq; Type: SEQUENCE; Schema: public; Owner: p1mps
--

ALTER TABLE public.dropship ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dropship_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mercenary_company; Type: TABLE; Schema: public; Owner: p1mps
--

CREATE TABLE public.mercenary_company (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    faction character varying(255) NOT NULL,
    reputation integer NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.mercenary_company OWNER TO p1mps;

--
-- Name: mercenary_company_id_seq; Type: SEQUENCE; Schema: public; Owner: p1mps
--

ALTER TABLE public.mercenary_company ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mercenary_company_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: messenger_messages; Type: TABLE; Schema: public; Owner: p1mps
--

CREATE TABLE public.messenger_messages (
    id bigint NOT NULL,
    body text NOT NULL,
    headers text NOT NULL,
    queue_name character varying(190) NOT NULL,
    created_at timestamp(0) without time zone NOT NULL,
    available_at timestamp(0) without time zone NOT NULL,
    delivered_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone
);


ALTER TABLE public.messenger_messages OWNER TO p1mps;

--
-- Name: messenger_messages_id_seq; Type: SEQUENCE; Schema: public; Owner: p1mps
--

ALTER TABLE public.messenger_messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.messenger_messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pilot; Type: TABLE; Schema: public; Owner: p1mps
--

CREATE TABLE public.pilot (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    is_named boolean NOT NULL,
    gunnery integer NOT NULL,
    piloting integer NOT NULL,
    gunnery_xp integer NOT NULL,
    company_id integer NOT NULL,
    piloting_xp integer NOT NULL
);


ALTER TABLE public.pilot OWNER TO p1mps;

--
-- Name: pilot_id_seq; Type: SEQUENCE; Schema: public; Owner: p1mps
--

ALTER TABLE public.pilot ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pilot_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: salvaged_mech; Type: TABLE; Schema: public; Owner: p1mps
--

CREATE TABLE public.salvaged_mech (
    id integer NOT NULL,
    model character varying(255) DEFAULT NULL::character varying,
    tonnage integer NOT NULL,
    bv_cost integer,
    contract_id integer,
    damage_state character varying(50) DEFAULT NULL::character varying,
    tech_base character varying(50) DEFAULT NULL::character varying,
    is_truly_destroyed boolean DEFAULT false NOT NULL,
    sp_taken integer,
    salvage_value integer,
    salvage_rights_percent integer,
    scrapyard boolean DEFAULT false NOT NULL,
    dropship_id integer,
    company_id integer NOT NULL,
    created_at timestamp(0) without time zone DEFAULT '1970-01-01 00:00:00'::timestamp without time zone NOT NULL
);


ALTER TABLE public.salvaged_mech OWNER TO p1mps;

--
-- Name: salvaged_mech_id_seq; Type: SEQUENCE; Schema: public; Owner: p1mps
--

ALTER TABLE public.salvaged_mech ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.salvaged_mech_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: support_point_entry; Type: TABLE; Schema: public; Owner: p1mps
--

CREATE TABLE public.support_point_entry (
    id integer NOT NULL,
    amount integer NOT NULL,
    description character varying(255) NOT NULL,
    created_at timestamp(0) without time zone NOT NULL,
    company_id integer NOT NULL
);


ALTER TABLE public.support_point_entry OWNER TO p1mps;

--
-- Name: support_point_entry_id_seq; Type: SEQUENCE; Schema: public; Owner: p1mps
--

ALTER TABLE public.support_point_entry ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.support_point_entry_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: track_record; Type: TABLE; Schema: public; Owner: p1mps
--

CREATE TABLE public.track_record (
    id integer NOT NULL,
    track_number integer NOT NULL,
    mission_type character varying(255) NOT NULL,
    terrain character varying(255) NOT NULL,
    command_complication text,
    combat_pay_tier character varying(50) DEFAULT NULL::character varying,
    status character varying(50) NOT NULL,
    created_at timestamp(0) without time zone NOT NULL,
    completed_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    contract_id integer NOT NULL,
    taking_one_for_team boolean NOT NULL
);


ALTER TABLE public.track_record OWNER TO p1mps;

--
-- Name: track_record_id_seq; Type: SEQUENCE; Schema: public; Owner: p1mps
--

ALTER TABLE public.track_record ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.track_record_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: unit; Type: TABLE; Schema: public; Owner: p1mps
--

CREATE TABLE public.unit (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    chassis character varying(255) NOT NULL,
    tonnage integer NOT NULL,
    bv integer NOT NULL,
    unit_type character varying(50) NOT NULL,
    damage_state character varying(50) NOT NULL,
    company_id integer NOT NULL,
    pilot_id integer,
    dropship_id integer
);


ALTER TABLE public.unit OWNER TO p1mps;

--
-- Name: unit_id_seq; Type: SEQUENCE; Schema: public; Owner: p1mps
--

ALTER TABLE public.unit ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.unit_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user; Type: TABLE; Schema: public; Owner: p1mps
--

CREATE TABLE public."user" (
    id integer NOT NULL,
    username character varying(180) NOT NULL,
    email character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    roles json DEFAULT '["ROLE_USER"]'::json NOT NULL
);


ALTER TABLE public."user" OWNER TO p1mps;

--
-- Name: user_id_seq; Type: SEQUENCE; Schema: public; Owner: p1mps
--

ALTER TABLE public."user" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: contract; Type: TABLE DATA; Schema: public; Owner: p1mps
--

COPY public.contract (id, is_opposing, type, employer, employer_affiliation, scale, duration_months, base_pay_percent, command_rights, support_terms, salvage_rights, transport_terms, number_of_tracks, tracks_completed, status, created_at, accepted_at, company_id, opposing_company_id, linked_contract_id, planet, intensity, name, description) FROM stdin;
2	f	raid	Corporation	Lyran Commonwealth	1	3	110	liaison	Straight/100%	10%	50%	2	2	completed	2026-06-26 09:49:50	2026-06-26 09:49:50	3	2	\N	Sommerset	0-0-2	Sommerset Steal the treasure (raider)	\N
4	f	garrison	Noble (Local)	Lyran Commonwealth	1	3	100	house	Straight/60%	30%	100%	2	2	completed	2026-06-27 09:40:45	2026-06-27 09:40:45	2	2	2	Sommerset	0-0-2	Sommerset Defender Contract	\N
8	f	raid	Pirates	Pirates	1	1	0	independent	0%	100%	0%	1	1	completed	2026-06-28 22:56:24	2026-06-28 22:56:24	2	\N	6	Sommerset	1	Act of piracy	\N
9	t	raid	Pirates	Pirates	1	1	0	independent	0%	100%	0%	1	1	completed	2026-06-29 09:06:30	\N	3	\N	6	Somerset	1	Raid	\N
20	f	invasion	Mercenary Subcontract	Pirate	1	6	50	liaison	Straight/40%	100%	25%	4	0	available	2026-08-02 11:17:07	\N	\N	\N	\N	Radostov	\N	\N	**CONTRACT PACKET: OPERATION SILENT ORBIT**\n**OFFERING ENTITY:** Meridian Logistics / Director Aris Thorne (Liao-Taurian Border Consortium)\n**THEATER:** The Sian Marches – Orbital Transfer Complex Kowloon-7\n**BRIEFING CLASSIFICATION:** PRE-CONTRACT ORIENTER // COMMAND PACKET\n\n---\n\n### 📜 SURFACE BRIEFING (Read Aloud or Hand to Players)\n\n*“The Sian Marches haven’t seen a JumpShip in four years. The Great Houses stopped subsidizing patrol routes after the last Succession War bled their treasuries dry. Now it’s just warlords, smugglers, and the quiet hum of abandoned factories. That’s why we’re here.*\n\n*Meridian Logistics has secured the lease on Kowloon-7. It’s an Orion-class orbital transfer station, sitting idle but structurally sound. Our priority is simple: clear the surface perimeter, reactivate the landing rings, and bring the long-range comms array online. Once it’s humming, we control the corridor.*\n\n*You’ll be compensated with full base pay, covered transport, and standard salvage rights on any derelict hardware you recover. Meridian handles the jumpship charter, the fuel, and the diplomatic waivers. In exchange, you establish a forward operating base, secure the landing pads, and keep the local militias from burning the place to the ground. Do that, and you don’t just get paid. You get a foothold. You get a base. You get to operate outside New Avalon and Liao’s notice.*\n\n*Watch your flanks. The Marches don’t forgive hesitation. But if you hold the rings, you hold the future.”*\n\n---\n\n### 🌍 STRATEGIC CONTEXT (GM Reference)\n\n**Era & Geopolitics:** Post-3050s border friction. The Great Houses are stretched thin by Clan border conflicts and internal succession crises. The Sian Marches, formerly a Lyran-Draconis border zone, have devolved into a deniable staging ground for Taurian Concordat and Combine remnant forces. Jumpship traffic is down 70%. Local "Free Marcher" militias control the surface, running black-market refineries and refugee smuggling routes.\n\n**Political Necessity:** The Combine has imposed an informal orbital blockade, choking helium-3 shipments and cutting off Taurian-aligned worlds. Meridian Logistics, a corporate shell masking a joint Liao-Taurian venture, is trying to break the blockade without triggering a formal declaration of war. They need a deniable, heavily armed mercenary force to seize and hold Kowloon-7.\n\n**Economic Reality:** The station isn’t just a military asset. It’s a tax-collecting transit hub. Whoever controls it can levy tariffs on JumpShip landings, control refugee flows, and monopolize rare-earth mineral exports from three adjacent systems. For a mercenary unit, it’s a generational opportunity to transition from contractors to sovereign operators.\n\n---\n\n### 🎯 WHAT THE EMPLOYER STANDS TO GAIN\n\n1. **Corridor Dominance:** Reactivating the station breaks the Combine’s informal blockade, allowing Meridian to control regional trade, fund a puppet government, or sell transit rights to the highest bidder.\n2. **Political Insurance:** Director Thorne is a minor house remnant leader facing exile. Securing Kowloon-7 gives him leverage to negotiate a noble title, secure asylum, or fund a covert coup back home.\n3. **Mercenary Proxy Force:** By funding your unit, Meridian secures a loyal, combat-tested force they can call upon during border disputes, without triggering Great House treaties or drawing official military intervention.\n4. **Data Arbitrage:** The station’s archives contain decades of SLDF movement logs, trade manifests, and black-site intelligence. Meridian plans to sell this data to intelligence brokers, minor houses, and independent JumpShip operators.\n\n---\n\n### 🕳️ CLASSIFIED ANNEX (GM ONLY / Withheld Intel)\n\n*Surface-level plausibility is maintained. The unit receives no mention of the following. If pressed, Meridian personnel will deflect, cite “operational security,” or offer a 5% bonus to drop the line.*\n\n1. **The Station Is Not Idle:** Kowloon-7’s defense network, an SLDF-era AI designated ARGUS-7, has been running autonomous counter-piracy protocols for 150 years. It classifies unauthorized landings as hostile. The “local militia” are actually remnant SLDF defense drones, automated turrets, and degraded support mechs that ARGUS-7 has been maintaining.\n2. **A Rival Force Is Already On-Planet:** A Clan scout detachment (unmarked, black-painted, flying under false Free Worlds League registrations) landed eight months ago. They’re not after the station. They’re conducting a systematic search for a buried Clan-era experimental mechsuite cache. They’ve already breached the lower vaults and are actively hunting intruders.\n3. **The Corporate Trap:** Meridian’s true contract isn’t to run the station. It’s to trigger its orbital self-destruct sequence if a Combine or Lyran fleet approaches. They plan to sacrifice your forward base to cover a political extraction. The “lease” is a temporary occupancy agreement, not a deed.\n4. **Salvage Restrictions:** Meridian reserves the right to confiscate any Class-A military tech, experimental armor, or pre-Cluster War weapons under “Corporate Security Protocol 9.” If your unit finds it, they will be forced to hand it over or face contract termination. The employer wants the hardware, not your upgrades.\n\n---\n\n### 🧭 COMMANDER’S DILEMMA (For Table Play)\n\n- **Accept the contract:** Secure a foothold, gain massive resources, but risk walking into automated defenses, a rival Clan force, and a corporate betrayal.\n- **Dig deeper:** Invest time and resources into local informants, satellite recon, or black-market contacts. Discover ARGUS-7’s protocols, the Clan presence, and Meridian’s self-destruct clauses before committing.\n- **Negotiate terms:** Demand higher salvage shares, explicit Clauses of Exemption, or a guaranteed exit strategy. Meridian may agree, stall, or try to bind your unit with debt.\n- **Walk away:** Preserve your force, but lose a generational opportunity. The corridor will be sealed by Great House fleets or warlord blockades within the year.\n\n*“In the Hinterlands, there are no clean victories. Only calculated losses, corporate contracts, and the will to hold the ground you take.”* \n**— Meridian Logistics, Pre-Contract Acknowledgment**\n\n---\n**GM NOTES FOR TABLE USE:**\n- Provide players with a basic map of Kowloon-7’s surface perimeter, comms array, landing rings, and lower vaults.\n- Use ARGUS-7’s automated defenses as dynamic environmental hazards (random turret activations, drone patrols, AI comms jamming).\n- The Clan scout team should operate as a rival mercenary force with different loadouts, tactics, and objectives. They may be willing to trade, fight, or temporarily cooperate if利益 align.\n- Track Meridian’s true endgame as a ticking clock. If players secure the station but ignore the self-destruct protocols, the employer may trigger it remotely unless players can bypass Meridian’s override codes.
6	f	garrison	Noble (Local)	Star league	1	3	100	independent	0%	60%	100%	2	2	completed	2026-06-27 09:44:37	2026-06-27 09:44:37	1	\N	\N	Somerset	0-1-1	Act of piracy contract	\N
14	f	retainer	Mercenary Subcontract	Periphery Power	1	6	70	independent	Straight/60%	10%	25%	4	0	available	2026-08-02 11:14:51	\N	\N	\N	\N	Eidsfoss	\N	\N	**CONTRACT DOSSIER: OPERATION IRON VEIL**\n**OFFERING ENTITY:** Charybdis Ventures / Lord-Proprietor Elias Vance (Lyran-Periphery Border Speculators)\n**THEATER:** The Kestrel Reach – Fractured Border Zone (Formerly FWL/Lyran contested space)\n**BRIEFING CLASSIFICATION:** COMMAND PACKET // PRE-CONTRACT ORIENTATION\n\n---\n\n### 📜 PLAYER-FACING BRIEFING (Read Aloud or Hand Out)\n\n*“The Jade Falcons pulled out three cycles ago, leaving the Kestrel Reach a graveyard of scorched earth and abandoned garrisons. What was once a bloody no-man’s-land between the Free Worlds League and the Lyran Commonwealth has become a goldmine for speculators, warlords, and ghosts. The Great Houses’ authority here has completely collapsed. Supply lines are dead. Jumpships don’t run clean routes. And the local militias? They answer to no one but their own survival.”*\n\n*“Charybdis Ventures is offering you a foothold. Not just salvage rights, but a permanent forward operating base. We’re funding your expedition to secure a rumored Star League-era logistics depot buried beneath the mountain ranges. Historical surveys suggest pre-Cluster War manufacturing data, functional mech bays, and intact production tooling. You secure the site, you establish a base, and you control the only viable jump corridor for the next fifty years.”*\n\n*“The political winds are shifting. The FWL’s central government is too fractured to project power. Lyran nobles are maneuvering in secret. If you move first, you don’t just get salvage. You get leverage. You get autonomy. You get to carve out a territory in a lawless sector where the only law is who holds the high ground and who controls the ore. Pay is aggressive. Salvage rights are heavily subsidized. Transportation and support are covered. We handle the paperwork. You handle the terrain.”*\n\n*“Do your recon. Watch your flanks. And don’t get attached to the rumors. The Reach doesn’t give up its secrets without a fight.”*\n\n---\n\n### 🔍 GEOPOLITICAL & STRATEGIC CONTEXT\n\nThe Kestrel Reach was carved out of a series of border skirmishes during the late Succession Wars, when the Draconis Combine and Lyran Commonwealth used proxy militias to bleed each other dry. With the recent Clan withdrawal and the collapse of several minor house governments, the region has devolved into a patchwork of warlord fiefdoms, black-market arms dealers, and desperate refugees. \n\nJumpship routes are unreliable due to unmarked minefields and pirate picket points. Local economies run on barter, stolen fuel, and unlicensed mech salvage. For a mercenary unit, this is a rare opportunity to operate outside Great House oversight, negotiate directly with local rulers, and build a self-sustaining fiefdom. \n\nCharybdis Ventures is a Lyran-FWL border consortium with deep ties to former SLDF logistics officers, independent jumpship operators, and Periphery black-market brokers. They don’t answer to Tharkad or New Avalon. They answer to profit, leverage, and survival.\n\n---\n\n### 🎯 WHAT THE EMPLOYER STANDS TO GAIN\n\n1. **Strategic Jump Control:** Securing the depot allows Charybdis to tax regional trade, control refugee flows, and block rival factions from establishing a foothold.\n2. **Star League Era Tech:** Recovering functional Star League manufacturing data or intact mech production lines could fund a generation of black-market sales or be traded for political favors with minor houses.\n3. **Political Insurance:** Lord-Proprietor Vance is facing a succession crisis back home. A successful expedition provides him with the leverage to negotiate his way into a minor noble title, or to fund a puppet government if his own house falls.\n4. **Mercenary Leverage:** By funding your unit, Charybdis secures a loyal, heavily armed proxy force they can call on during border disputes, without triggering Great House treaties or drawing official military intervention.\n\n---\n\n### 🕳️ CLASSIFIED ANNEX (GM ONLY / Withheld Intel)\n\n*Surface-level plausibility is maintained. The unit receives no mention of the following. If pressed, Charybdis personnel will deflect, cite “operational security,” or offer a 10% bonus to drop the line.*\n\n1. **The Site Is Active:** The depot isn’t abandoned. It’s running on automated defense grids, maintenance drones, and localized power plants that haven’t been powered down in 200 years. The “abandoned” status is a cover. The facility is actively filtering for intruders.\n2. **A Rival Unit Is Already On-Planet:** A heavily sanctioned Combine-backed mercenary outfit (flying unmarked, black-painted mechs) landed six months ago. They’re not after salvage. They’re conducting a systematic purge of the facility’s upper levels. Their commander is a former SLDF officer turned warlord.\n3. **The Cargo Is Unstable:** The depot contains experimental Clan-era countermeasures and sealed canisters of pre-Cluster War chemical agents. One breach could contaminate water tables, fry electronics, or trigger environmental collapse. Charybdis downplays this because they need the unit to breach the lower vaults first.\n4. **Political Expendability:** If the FWL or Lyran Commonwealth moves to reassert control, Charybdis will cut funding and denounce the contract as a rogue operation. Your unit will be left holding the bag, the base, and the wrath of two Great Houses. The employer’s true endgame is to test your unit’s loyalty and combat effectiveness before committing to a larger proxy war.\n5. **The Real Prize Isn’t the Tech:** The depot houses a buried SLDF-era command bunker containing encrypted troop movement logs and black-site intelligence. Charybdis doesn’t care about the mechs. They care about who moved where, when, and why. They’re building a ledger of Great House failures to sell to the highest bidder.\n\n---\n\n### 🧭 COMMANDER’S DILEMMA (For Table Play)\n\n- **Accept the contract:** Secure a foothold, gain massive resources, but risk walking into an active fortress, a rival mercenary force, and a political trap.\n- **Dig deeper:** Invest time and resources into local informants, black-market contacts, or satellite recon. Discover the rival unit, the automated defenses, and the chemical hazards before committing.\n- **Negotiate terms:** Demand higher salvage shares, explicit Clauses of Exemption, or an exit strategy. Charybdis may agree, stall, or try to bind your unit with debt.\n- **Walk away:** Preserve your force, but lose a generational opportunity. The Reach will be swept by warlords or Great House recon forces within the year.\n\n*“In the Hinterlands, there are no clean victories. Only calculated losses and the will to hold the ground you take.”* \n**— Charybdis Ventures, Pre-Contract Acknowledgment**
29	f	retainer	House Government	Draconis Combine	1	6	100	integrated	Straight/100%	None	50%	4	0	available	2026-08-10 22:22:13	\N	\N	\N	\N	Eidsfoss	\N	\N	
\.


--
-- Data for Name: contract_log_entry; Type: TABLE DATA; Schema: public; Owner: p1mps
--

COPY public.contract_log_entry (id, month, entry_type, description, roll_result, data, created_at, contract_id, track_id, support_point_entry_id) FROM stdin;
71	1	transport	Transport: 50 + (50 × 2) = 150 SP total — employer covers 100% (+150 SP) → player pays -0 SP	\N	\N	2026-06-27 23:57:56	4	\N	53
73	1	maintenance	Maintenance deducted: -500 SP	\N	\N	2026-06-27 23:58:23	4	\N	55
75	1	base_pay	Base pay received: +500 SP	\N	\N	2026-06-27 23:59:08	4	\N	57
80	2	maintenance	Maintenance deducted: -500 SP	\N	\N	2026-06-27 23:59:55	4	\N	60
81	2	base_pay	Base pay received: +500 SP	\N	\N	2026-06-27 23:59:58	4	\N	61
82	3	maintenance	Maintenance deducted: -500 SP	\N	\N	2026-06-28 00:00:05	4	\N	62
83	3	base_pay	Base pay received: +500 SP	\N	\N	2026-06-28 00:00:09	4	\N	63
89	3	post_track	Combat pay: none (none). No salvage.	\N	\N	2026-06-28 00:34:00	4	\N	\N
87	3	track_setup	Track 1: Reconnaissance on Desert (MegaMek: Desert)	\N	{"missionType":"Reconnaissance","missionRoll":2,"terrain":"Desert","terrainSetting":"Desert","terrainRoll":5,"complication":"No Complication [cite: 887]","complicationRoll":8}	2026-06-28 00:04:46	4	6	\N
92	1	maintenance	Maintenance deducted: -500 SP	\N	\N	2026-06-28 18:47:40	6	\N	65
93	1	base_pay	Base pay received: +500 SP	\N	\N	2026-06-28 18:47:46	6	\N	66
95	1	maintenance	Maintenance deducted: -500 SP	\N	\N	2026-06-28 19:20:31	2	\N	69
96	1	base_pay	Base pay received: +550 SP	\N	\N	2026-06-28 19:20:34	2	\N	70
99	2	maintenance	Maintenance deducted: -500 SP	\N	\N	2026-06-28 19:21:34	2	\N	72
100	2	base_pay	Base pay received: +550 SP	\N	\N	2026-06-28 19:21:37	2	\N	73
116	1	track_setup	Track 1: Reconnaissance on Wetlands (MegaMek: Swamp) [TOFTT]	\N	{"missionType":"Reconnaissance","missionRoll":4,"terrain":"Wetlands","terrainSetting":"Swamp","terrainRoll":3,"complication":"The muck of the wetlands is fouling up vehicle systems. Reduce all your units with either Wheeled or Tracked MP by 1 for the first three rounds of combat. [cite: 1293, 1294]","complicationRoll":5}	2026-06-29 09:18:39	9	14	\N
103	3	maintenance	Maintenance deducted: -500 SP	\N	\N	2026-06-28 19:22:43	2	\N	75
104	3	base_pay	Base pay received: +550 SP	\N	\N	2026-06-28 19:22:48	2	\N	76
105	3	track_setup	Track 1: Reconnaissance on Desert (MegaMek: Desert)	\N	{"missionType":"Reconnaissance","missionRoll":6,"terrain":"Desert","terrainSetting":"Desert","terrainRoll":5,"complication":"No Complication [cite: 1011]","complicationRoll":4}	2026-06-28 19:23:22	2	11	\N
106	3	post_track	Combat pay: +250 SP (half). No salvage.	\N	\N	2026-06-28 19:23:49	2	\N	77
108	2	maintenance	Maintenance deducted: -500 SP	\N	\N	2026-06-28 19:30:36	6	\N	78
109	2	base_pay	Base pay received: +500 SP	\N	\N	2026-06-28 19:30:38	6	\N	79
117	1	post_track	Combat pay: +62 SP (full) (TOFTT — half pay). No salvage.	\N	\N	2026-06-29 09:18:45	9	\N	83
110	2	track_setup	Track 1: Reconnaissance on Desert (MegaMek: Desert)	\N	{"missionType":"Reconnaissance","missionRoll":1,"terrain":"Desert","terrainSetting":"Desert","terrainRoll":8,"complication":"The desert sun is reducing the efficacy of your heatsinks. All heat tracking units suffer from +2 heat every turn. [cite: 888, 889]","complicationRoll":2}	2026-06-28 19:30:44	6	12	\N
111	2	post_track	Combat pay: none (none). No salvage.	\N	\N	2026-06-28 22:54:21	6	\N	\N
112	1	track_setup	Track 1: Reconnaissance on Desert (MegaMek: Desert) [TOFTT]	\N	{"missionType":"Reconnaissance","missionRoll":1,"terrain":"Desert","terrainSetting":"Desert","terrainRoll":5,"complication":"No Complication [cite: 1011]","complicationRoll":4}	2026-06-28 23:00:21	8	13	\N
118	3	downtime	Repair Jade Hawk 	\N	\N	2026-06-29 12:07:52	2	\N	\N
114	1	post_track	Combat pay: +62 SP (full) (TOFTT — half pay). No salvage.	\N	\N	2026-06-29 09:06:19	8	\N	81
119	4	maintenance	Maintenance deducted: -500 SP	\N	\N	2026-07-26 20:10:23	4	\N	86
120	4	base_pay	Base pay received: +500 SP	\N	\N	2026-07-26 20:10:30	4	\N	87
125	4	track_setup	Track 2: Demolition on Grasslands (MegaMek: Default)	\N	{"missionType":"Demolition","missionRoll":6,"terrain":"Grasslands","terrainSetting":"Default","terrainRoll":7,"complication":"\\"\\"","complicationRoll":6}	2026-07-26 20:19:52	2	16	\N
121	4	track_setup	Track 2: Demolition on Grasslands (MegaMek: Default)	\N	{"missionType":"Demolition","missionRoll":6,"terrain":"Grasslands","terrainSetting":"Default","terrainRoll":3,"complication":"\\"\\"","complicationRoll":6}	2026-07-26 20:10:40	4	15	\N
122	4	post_track	Combat pay: +500 SP (full). No salvage.	\N	\N	2026-07-26 20:19:15	4	\N	88
123	4	maintenance	Maintenance deducted: -500 SP	\N	\N	2026-07-26 20:19:45	2	\N	89
124	4	base_pay	Base pay received: +550 SP	\N	\N	2026-07-26 20:19:49	2	\N	90
126	4	post_track	Combat pay: none (none). No salvage.	\N	\N	2026-07-26 20:20:13	2	\N	\N
133	4	post_track	Combat pay: +500 SP (full). No salvage.	\N	\N	2026-08-01 00:25:59	6	\N	98
131	3	base_pay	Base pay received: +500 SP	\N	\N	2026-07-31 22:39:45	6	\N	96
132	3	maintenance	Maintenance deducted: -500 SP	\N	\N	2026-07-31 22:39:49	6	\N	97
\.


--
-- Data for Name: doctrine_migration_versions; Type: TABLE DATA; Schema: public; Owner: p1mps
--

COPY public.doctrine_migration_versions (version, executed_at, execution_time) FROM stdin;
DoctrineMigrations\\Version20260624121344	2026-06-25 11:52:05	239
DoctrineMigrations\\Version20260624134538	2026-06-25 11:52:05	2
DoctrineMigrations\\Version20260624165605	2026-06-25 11:52:05	2
DoctrineMigrations\\Version20260626204505	2026-06-26 20:46:45	7
DoctrineMigrations\\Version20260628015000	2026-06-27 23:55:25	51
DoctrineMigrations\\Version20260629201811	2026-06-30 15:06:21	65
DoctrineMigrations\\Version20260629213757	2026-06-30 15:06:21	1
DoctrineMigrations\\Version20260630200412	2026-07-31 22:02:09	141
DoctrineMigrations\\Version20260728212335	2026-07-31 22:02:09	21
DoctrineMigrations\\Version20260729000001	2026-07-31 22:02:09	5
DoctrineMigrations\\Version20260729120000	2026-07-31 22:02:09	24
DoctrineMigrations\\Version20260729210202	2026-07-31 22:02:09	1
DoctrineMigrations\\Version20260731083825	2026-07-31 22:02:09	57
DoctrineMigrations\\Version20260731093631	2026-07-31 22:02:09	1
DoctrineMigrations\\Version20260731185500	2026-08-01 00:25:35	9
DoctrineMigrations\\Version20260804164637	2026-08-05 13:50:02	130
DoctrineMigrations\\Version20260806085522	2026-08-06 16:12:12	18
DoctrineMigrations\\Version20260806090000	2026-08-06 20:57:07	8
DoctrineMigrations\\Version20260809144115	2026-08-10 08:32:21	36
DoctrineMigrations\\Version20260809145957	2026-08-10 08:32:21	7
\.


--
-- Data for Name: dropship; Type: TABLE DATA; Schema: public; Owner: p1mps
--

COPY public.dropship (id, max_capacity, company_id, name, mekbay_capacity) FROM stdin;
1	1000	2	Warbound	4
2	500	3	Perfect Storm	4
\.


--
-- Data for Name: mercenary_company; Type: TABLE DATA; Schema: public; Owner: p1mps
--

COPY public.mercenary_company (id, name, faction, reputation, user_id) FROM stdin;
1	Mitchell's Mongrels	Mercenary	1	1
2	The scavengers 1st force	Raven alliance	1	2
3	Peregrine's Outcast	Jade Falcon	1	3
\.


--
-- Data for Name: messenger_messages; Type: TABLE DATA; Schema: public; Owner: p1mps
--

COPY public.messenger_messages (id, body, headers, queue_name, created_at, available_at, delivered_at) FROM stdin;
\.


--
-- Data for Name: pilot; Type: TABLE DATA; Schema: public; Owner: p1mps
--

COPY public.pilot (id, name, is_named, gunnery, piloting, gunnery_xp, company_id, piloting_xp) FROM stdin;
2	Scrappy	t	4	5	0	2	0
5	Elena "Ratch" Rostov	t	4	5	0	3	0
4	Chase Falcon	t	4	5	40	3	0
3	Samantha Hazel	t	4	5	0	3	0
1	Pitch Black	t	4	5	0	2	0
\.


--
-- Data for Name: salvaged_mech; Type: TABLE DATA; Schema: public; Owner: p1mps
--

COPY public.salvaged_mech (id, model, tonnage, bv_cost, contract_id, damage_state, tech_base, is_truly_destroyed, sp_taken, salvage_value, salvage_rights_percent, scrapyard, dropship_id, company_id, created_at) FROM stdin;
11	Phoenix Hawk PXH-3K	45	1380	\N	none	\N	f	\N	\N	\N	t	\N	2	2026-08-11 06:32:13
12	Hunchback HBK-5N	50	1485	\N	crippled	\N	f	\N	\N	\N	t	\N	2	2026-08-11 06:32:16
13	Marauder MAD-5D	60	1790	\N	crippled	\N	f	\N	\N	\N	t	\N	2	2026-08-11 06:32:18
14	Marauder MAD-5D	60	1790	\N	crippled	\N	f	\N	\N	\N	t	\N	1	2026-08-11 11:20:06
15	Blackjack BJ-2	45	1265	\N	none	\N	f	\N	\N	\N	t	\N	1	2026-08-11 11:20:08
16	Maelstrom MTR-5K	55	1620	\N	structural	\N	f	\N	\N	\N	t	\N	1	2026-08-11 11:20:11
17	Gallowglas GAL-1GLS	45	1425	\N	none	\N	f	\N	\N	\N	t	\N	3	2026-08-11 11:54:01
18	Vindicator VND-3L	45	1520	\N	structural	\N	f	\N	\N	\N	t	\N	3	2026-08-11 11:54:03
19	Wasp WSP-3S	25	389	\N	structural	\N	f	\N	\N	\N	t	\N	3	2026-08-11 11:54:04
\.


--
-- Data for Name: support_point_entry; Type: TABLE DATA; Schema: public; Owner: p1mps
--

COPY public.support_point_entry (id, amount, description, created_at, company_id) FROM stdin;
60	-500	Contract maintenance (scale 1)	2026-06-27 23:59:55	2
61	500	Base pay (scale 1)	2026-06-27 23:59:58	2
62	-500	Contract maintenance (scale 1)	2026-06-28 00:00:05	2
63	500	Base pay (scale 1)	2026-06-28 00:00:09	2
65	-500	Contract maintenance (scale 1)	2026-06-28 18:47:40	1
66	500	Base pay (scale 1)	2026-06-28 18:47:46	1
67	3000	Starting points	2026-06-27 23:57:45	1
68	3000	Starting points	2026-06-27 23:57:45	3
69	-500	Contract maintenance (scale 1)	2026-06-28 19:20:31	3
70	550	Base pay (scale 1)	2026-06-28 19:20:34	3
72	-500	Contract maintenance (scale 1)	2026-06-28 19:21:34	3
73	550	Base pay (scale 1)	2026-06-28 19:21:37	3
75	-500	Contract maintenance (scale 1)	2026-06-28 19:22:43	3
76	550	Base pay (scale 1)	2026-06-28 19:22:48	3
77	250	Combat pay (half)	2026-06-28 19:23:49	3
78	-500	Contract maintenance (scale 1)	2026-06-28 19:30:36	1
79	500	Base pay (scale 1)	2026-06-28 19:30:38	1
81	62	Combat pay (full)	2026-06-29 09:06:19	2
83	62	Combat pay (full)	2026-06-29 09:18:45	3
84	-300	Travel to Almotecan	2026-07-23 17:05:53	3
85	-2223	Black Hawk-KU OR	2026-07-23 17:06:14	3
86	-500	Contract maintenance (scale 1)	2026-07-26 20:10:23	2
87	500	Base pay (scale 1)	2026-07-26 20:10:30	2
88	500	Combat pay (full)	2026-07-26 20:19:15	2
89	-500	Contract maintenance (scale 1)	2026-07-26 20:19:45	3
90	550	Base pay (scale 1)	2026-07-26 20:19:49	3
92	-50	Travel to Almotacen base fee	2026-07-26 21:03:08	3
96	500	Base pay (scale 1)	2026-07-31 22:39:45	1
97	-500	Contract maintenance (scale 1)	2026-07-31 22:39:49	1
98	500	Combat pay (full)	2026-08-01 00:25:59	1
52	3000	Starting points	2026-06-27 23:57:45	2
53	0	Transport (2 jumps)	2026-06-27 23:57:56	2
55	-500	Contract maintenance (scale 1)	2026-06-27 23:58:23	2
57	500	Base pay (scale 1)	2026-06-27 23:59:08	2
\.


--
-- Data for Name: track_record; Type: TABLE DATA; Schema: public; Owner: p1mps
--

COPY public.track_record (id, track_number, mission_type, terrain, command_complication, combat_pay_tier, status, created_at, completed_at, contract_id, taking_one_for_team) FROM stdin;
10	1	Reconnaissance	Desert	No Complication [cite: 1242]	none	completed	2026-06-28 19:21:44	2026-07-26 20:20:13	2	f
17	2	Secure	Urban	High mountain passes cause issues for some vehicles. All units with Hover or VTOL MP reduce their cruising MP by 2 due to the thin atmosphere. BSPs with hover or VTOL movement reduce their total MP by 2. [cite: 1125, 1126]	\N	pending	2026-07-31 22:36:54	\N	6	f
12	1	Reconnaissance	Desert	No Complication [cite: 1183]	full	completed	2026-06-28 19:30:44	2026-08-01 00:25:59	6	f
6	1	Reconnaissance	Desert	No Complication [cite: 1011]	none	completed	2026-06-28 00:04:46	2026-06-28 00:34:00	4	f
11	1	Reconnaissance	Desert	No Complication [cite: 1011]	\N	pending	2026-06-28 19:23:22	\N	2	f
9	1	Reconnaissance	Desert	No Complication [cite: 975]	half	completed	2026-06-28 19:20:38	2026-06-28 19:23:49	2	f
8	1	Reconnaissance	Desert	No Complication [cite: 975]	none	completed	2026-06-28 19:15:36	2026-06-28 22:54:21	6	f
13	1	Reconnaissance	Desert	No Complication [cite: 1011]	full	completed	2026-06-28 23:00:21	2026-06-29 09:06:19	8	t
14	1	Reconnaissance	Wetlands	The muck of the wetlands is fouling up vehicle systems. Reduce all your units with either Wheeled or Tracked MP by 1 for the first three rounds of combat. [cite: 1293, 1294]	full	completed	2026-06-29 09:18:39	2026-06-29 09:18:45	9	t
15	2	Demolition	Grasslands	Local support was limited at best. All your support units are 5/6. This does not affect the BV of selected support units and give you more to select. If using BSPs, then you may not purchase any Veteran Assets. [cite: 1295, 1296]	full	completed	2026-07-26 20:10:40	2026-07-26 20:19:15	4	f
16	2	Demolition	Grasslands	A point of Elementals has joined the battle on your opponent's side, seeking honor and glory in battle. Add a 3/4 Elemental III Battle Armor [Flamer] (Sqd5) to your opponent's force (this unit does not count toward their support unit limit). If you should destroy this unit using only a single one of your units, then at the conclusion of this track you will have the option to acquire the unit and add it to your roster permanently for 500 SP (If the squad takes any damage from a second unit then you will lose the ability to acquire this unit). If using BSPs, then just add 1 Veteran Elemental III unit to the opponent's support for this track. [cite: 979, 980, 981, 982]	\N	pending	2026-07-26 20:19:52	\N	2	f
\.


--
-- Data for Name: unit; Type: TABLE DATA; Schema: public; Owner: p1mps
--

COPY public.unit (id, name, chassis, tonnage, bv, unit_type, damage_state, company_id, pilot_id, dropship_id) FROM stdin;
1	Event Horizon	Black Hawk (Nova) S	50	2056	mech	none	2	1	\N
2	Distant Thunder	Whitworth WTH-2	40	936	mech	none	2	2	\N
3	Tempest's Edge	Jade Hawk	75	2523	mech	none	3	3	2
4	Augur	Tribune Mobile Tactical Command HQ	30	424	vehicle	none	3	4	2
5	Thunderhead	Black Hawk-KU [BHKU-OR]	60	2193	mech	none	3	\N	2
\.


--
-- Data for Name: user; Type: TABLE DATA; Schema: public; Owner: p1mps
--

COPY public."user" (id, username, email, password, roles) FROM stdin;
2	Andrea	imparato.andrea@gmail.com	$2y$13$3894MxDJgJy4B25Wulz5uOXAGeW.qJA1q6CYxIF0BOPDDjf2LoMVq	["ROLE_USER"]
1	MitchellWelsh	mitchellcwelsh@outlook.com	$2y$13$UCLE0vXuNBq.ZIM.BpjO6.2mXFlf4pjXEchL0ifG4Q.p0hXbpQ4u2	["ROLE_USER"]
3	Zidahya	zidahya@gmx.net	$2y$13$Ht91GVH2WJqw16ELCR2zLe/QXlnyh61HBCuzRzL.1OISd7LfNdcLW	["ROLE_USER"]
\.


--
-- Name: contract_id_seq; Type: SEQUENCE SET; Schema: public; Owner: p1mps
--

SELECT pg_catalog.setval('public.contract_id_seq', 29, true);


--
-- Name: contract_log_entry_id_seq; Type: SEQUENCE SET; Schema: public; Owner: p1mps
--

SELECT pg_catalog.setval('public.contract_log_entry_id_seq', 133, true);


--
-- Name: dropship_id_seq; Type: SEQUENCE SET; Schema: public; Owner: p1mps
--

SELECT pg_catalog.setval('public.dropship_id_seq', 2, true);


--
-- Name: mercenary_company_id_seq; Type: SEQUENCE SET; Schema: public; Owner: p1mps
--

SELECT pg_catalog.setval('public.mercenary_company_id_seq', 3, true);


--
-- Name: messenger_messages_id_seq; Type: SEQUENCE SET; Schema: public; Owner: p1mps
--

SELECT pg_catalog.setval('public.messenger_messages_id_seq', 1, false);


--
-- Name: pilot_id_seq; Type: SEQUENCE SET; Schema: public; Owner: p1mps
--

SELECT pg_catalog.setval('public.pilot_id_seq', 5, true);


--
-- Name: salvaged_mech_id_seq; Type: SEQUENCE SET; Schema: public; Owner: p1mps
--

SELECT pg_catalog.setval('public.salvaged_mech_id_seq', 19, true);


--
-- Name: support_point_entry_id_seq; Type: SEQUENCE SET; Schema: public; Owner: p1mps
--

SELECT pg_catalog.setval('public.support_point_entry_id_seq', 98, true);


--
-- Name: track_record_id_seq; Type: SEQUENCE SET; Schema: public; Owner: p1mps
--

SELECT pg_catalog.setval('public.track_record_id_seq', 17, true);


--
-- Name: unit_id_seq; Type: SEQUENCE SET; Schema: public; Owner: p1mps
--

SELECT pg_catalog.setval('public.unit_id_seq', 5, true);


--
-- Name: user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: p1mps
--

SELECT pg_catalog.setval('public.user_id_seq', 3, true);


--
-- Name: contract_log_entry contract_log_entry_pkey; Type: CONSTRAINT; Schema: public; Owner: p1mps
--

ALTER TABLE ONLY public.contract_log_entry
    ADD CONSTRAINT contract_log_entry_pkey PRIMARY KEY (id);


--
-- Name: contract contract_pkey; Type: CONSTRAINT; Schema: public; Owner: p1mps
--

ALTER TABLE ONLY public.contract
    ADD CONSTRAINT contract_pkey PRIMARY KEY (id);


--
-- Name: doctrine_migration_versions doctrine_migration_versions_pkey; Type: CONSTRAINT; Schema: public; Owner: p1mps
--

ALTER TABLE ONLY public.doctrine_migration_versions
    ADD CONSTRAINT doctrine_migration_versions_pkey PRIMARY KEY (version);


--
-- Name: dropship dropship_pkey; Type: CONSTRAINT; Schema: public; Owner: p1mps
--

ALTER TABLE ONLY public.dropship
    ADD CONSTRAINT dropship_pkey PRIMARY KEY (id);


--
-- Name: mercenary_company mercenary_company_pkey; Type: CONSTRAINT; Schema: public; Owner: p1mps
--

ALTER TABLE ONLY public.mercenary_company
    ADD CONSTRAINT mercenary_company_pkey PRIMARY KEY (id);


--
-- Name: messenger_messages messenger_messages_pkey; Type: CONSTRAINT; Schema: public; Owner: p1mps
--

ALTER TABLE ONLY public.messenger_messages
    ADD CONSTRAINT messenger_messages_pkey PRIMARY KEY (id);


--
-- Name: pilot pilot_pkey; Type: CONSTRAINT; Schema: public; Owner: p1mps
--

ALTER TABLE ONLY public.pilot
    ADD CONSTRAINT pilot_pkey PRIMARY KEY (id);


--
-- Name: salvaged_mech salvaged_mech_pkey; Type: CONSTRAINT; Schema: public; Owner: p1mps
--

ALTER TABLE ONLY public.salvaged_mech
    ADD CONSTRAINT salvaged_mech_pkey PRIMARY KEY (id);


--
-- Name: support_point_entry support_point_entry_pkey; Type: CONSTRAINT; Schema: public; Owner: p1mps
--

ALTER TABLE ONLY public.support_point_entry
    ADD CONSTRAINT support_point_entry_pkey PRIMARY KEY (id);


--
-- Name: track_record track_record_pkey; Type: CONSTRAINT; Schema: public; Owner: p1mps
--

ALTER TABLE ONLY public.track_record
    ADD CONSTRAINT track_record_pkey PRIMARY KEY (id);


--
-- Name: unit unit_pkey; Type: CONSTRAINT; Schema: public; Owner: p1mps
--

ALTER TABLE ONLY public.unit
    ADD CONSTRAINT unit_pkey PRIMARY KEY (id);


--
-- Name: user user_pkey; Type: CONSTRAINT; Schema: public; Owner: p1mps
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT user_pkey PRIMARY KEY (id);


--
-- Name: idx_26c82ebb2576e0fd; Type: INDEX; Schema: public; Owner: p1mps
--

CREATE INDEX idx_26c82ebb2576e0fd ON public.contract_log_entry USING btree (contract_id);


--
-- Name: idx_26c82ebb5ed23c43; Type: INDEX; Schema: public; Owner: p1mps
--

CREATE INDEX idx_26c82ebb5ed23c43 ON public.contract_log_entry USING btree (track_id);


--
-- Name: idx_5d56e8c3979b1ad6; Type: INDEX; Schema: public; Owner: p1mps
--

CREATE INDEX idx_5d56e8c3979b1ad6 ON public.support_point_entry USING btree (company_id);


--
-- Name: idx_75ea56e0fb7336f0e3bd61ce16ba31dbbf396750; Type: INDEX; Schema: public; Owner: p1mps
--

CREATE INDEX idx_75ea56e0fb7336f0e3bd61ce16ba31dbbf396750 ON public.messenger_messages USING btree (queue_name, available_at, delivered_at, id);


--
-- Name: idx_8d1e5f52979b1ad6; Type: INDEX; Schema: public; Owner: p1mps
--

CREATE INDEX idx_8d1e5f52979b1ad6 ON public.pilot USING btree (company_id);


--
-- Name: idx_d3f65e782576e0fd; Type: INDEX; Schema: public; Owner: p1mps
--

CREATE INDEX idx_d3f65e782576e0fd ON public.track_record USING btree (contract_id);


--
-- Name: idx_dcbb0c53979b1ad6; Type: INDEX; Schema: public; Owner: p1mps
--

CREATE INDEX idx_dcbb0c53979b1ad6 ON public.unit USING btree (company_id);


--
-- Name: idx_dcbb0c539863015; Type: INDEX; Schema: public; Owner: p1mps
--

CREATE INDEX idx_dcbb0c539863015 ON public.unit USING btree (dropship_id);


--
-- Name: idx_e98f2859979b1ad6; Type: INDEX; Schema: public; Owner: p1mps
--

CREATE INDEX idx_e98f2859979b1ad6 ON public.contract USING btree (company_id);


--
-- Name: idx_e98f2859ea4ebd8c; Type: INDEX; Schema: public; Owner: p1mps
--

CREATE INDEX idx_e98f2859ea4ebd8c ON public.contract USING btree (opposing_company_id);


--
-- Name: idx_f1533ac52576e0fd; Type: INDEX; Schema: public; Owner: p1mps
--

CREATE INDEX idx_f1533ac52576e0fd ON public.salvaged_mech USING btree (contract_id);


--
-- Name: idx_f1533ac5979b1ad6; Type: INDEX; Schema: public; Owner: p1mps
--

CREATE INDEX idx_f1533ac5979b1ad6 ON public.salvaged_mech USING btree (company_id);


--
-- Name: idx_f1533ac59863015; Type: INDEX; Schema: public; Owner: p1mps
--

CREATE INDEX idx_f1533ac59863015 ON public.salvaged_mech USING btree (dropship_id);


--
-- Name: uniq_26c82ebbe1076051; Type: INDEX; Schema: public; Owner: p1mps
--

CREATE UNIQUE INDEX uniq_26c82ebbe1076051 ON public.contract_log_entry USING btree (support_point_entry_id);


--
-- Name: uniq_6461c2ca76ed395; Type: INDEX; Schema: public; Owner: p1mps
--

CREATE UNIQUE INDEX uniq_6461c2ca76ed395 ON public.mercenary_company USING btree (user_id);


--
-- Name: uniq_8d93d649e7927c74; Type: INDEX; Schema: public; Owner: p1mps
--

CREATE UNIQUE INDEX uniq_8d93d649e7927c74 ON public."user" USING btree (email);


--
-- Name: uniq_8d93d649f85e0677; Type: INDEX; Schema: public; Owner: p1mps
--

CREATE UNIQUE INDEX uniq_8d93d649f85e0677 ON public."user" USING btree (username);


--
-- Name: uniq_9170d952979b1ad6; Type: INDEX; Schema: public; Owner: p1mps
--

CREATE UNIQUE INDEX uniq_9170d952979b1ad6 ON public.dropship USING btree (company_id);


--
-- Name: uniq_dcbb0c53ce55439b; Type: INDEX; Schema: public; Owner: p1mps
--

CREATE UNIQUE INDEX uniq_dcbb0c53ce55439b ON public.unit USING btree (pilot_id);


--
-- Name: contract_log_entry fk_26c82ebb2576e0fd; Type: FK CONSTRAINT; Schema: public; Owner: p1mps
--

ALTER TABLE ONLY public.contract_log_entry
    ADD CONSTRAINT fk_26c82ebb2576e0fd FOREIGN KEY (contract_id) REFERENCES public.contract(id);


--
-- Name: contract_log_entry fk_26c82ebb5ed23c43; Type: FK CONSTRAINT; Schema: public; Owner: p1mps
--

ALTER TABLE ONLY public.contract_log_entry
    ADD CONSTRAINT fk_26c82ebb5ed23c43 FOREIGN KEY (track_id) REFERENCES public.track_record(id);


--
-- Name: support_point_entry fk_5d56e8c3979b1ad6; Type: FK CONSTRAINT; Schema: public; Owner: p1mps
--

ALTER TABLE ONLY public.support_point_entry
    ADD CONSTRAINT fk_5d56e8c3979b1ad6 FOREIGN KEY (company_id) REFERENCES public.mercenary_company(id);


--
-- Name: mercenary_company fk_6461c2ca76ed395; Type: FK CONSTRAINT; Schema: public; Owner: p1mps
--

ALTER TABLE ONLY public.mercenary_company
    ADD CONSTRAINT fk_6461c2ca76ed395 FOREIGN KEY (user_id) REFERENCES public."user"(id);


--
-- Name: contract_log_entry fk_70799797a7b9b420; Type: FK CONSTRAINT; Schema: public; Owner: p1mps
--

ALTER TABLE ONLY public.contract_log_entry
    ADD CONSTRAINT fk_70799797a7b9b420 FOREIGN KEY (support_point_entry_id) REFERENCES public.support_point_entry(id) ON DELETE SET NULL;


--
-- Name: pilot fk_8d1e5f52979b1ad6; Type: FK CONSTRAINT; Schema: public; Owner: p1mps
--

ALTER TABLE ONLY public.pilot
    ADD CONSTRAINT fk_8d1e5f52979b1ad6 FOREIGN KEY (company_id) REFERENCES public.mercenary_company(id);


--
-- Name: dropship fk_9170d952979b1ad6; Type: FK CONSTRAINT; Schema: public; Owner: p1mps
--

ALTER TABLE ONLY public.dropship
    ADD CONSTRAINT fk_9170d952979b1ad6 FOREIGN KEY (company_id) REFERENCES public.mercenary_company(id);


--
-- Name: salvaged_mech fk_bcbca8949b5b7f0; Type: FK CONSTRAINT; Schema: public; Owner: p1mps
--

ALTER TABLE ONLY public.salvaged_mech
    ADD CONSTRAINT fk_bcbca8949b5b7f0 FOREIGN KEY (contract_id) REFERENCES public.contract(id) ON DELETE SET NULL;


--
-- Name: track_record fk_d3f65e782576e0fd; Type: FK CONSTRAINT; Schema: public; Owner: p1mps
--

ALTER TABLE ONLY public.track_record
    ADD CONSTRAINT fk_d3f65e782576e0fd FOREIGN KEY (contract_id) REFERENCES public.contract(id);


--
-- Name: unit fk_dcbb0c53979b1ad6; Type: FK CONSTRAINT; Schema: public; Owner: p1mps
--

ALTER TABLE ONLY public.unit
    ADD CONSTRAINT fk_dcbb0c53979b1ad6 FOREIGN KEY (company_id) REFERENCES public.mercenary_company(id);


--
-- Name: unit fk_dcbb0c539863015; Type: FK CONSTRAINT; Schema: public; Owner: p1mps
--

ALTER TABLE ONLY public.unit
    ADD CONSTRAINT fk_dcbb0c539863015 FOREIGN KEY (dropship_id) REFERENCES public.dropship(id) ON DELETE SET NULL;


--
-- Name: unit fk_dcbb0c53ce55439b; Type: FK CONSTRAINT; Schema: public; Owner: p1mps
--

ALTER TABLE ONLY public.unit
    ADD CONSTRAINT fk_dcbb0c53ce55439b FOREIGN KEY (pilot_id) REFERENCES public.pilot(id);


--
-- Name: contract fk_e98f2859979b1ad6; Type: FK CONSTRAINT; Schema: public; Owner: p1mps
--

ALTER TABLE ONLY public.contract
    ADD CONSTRAINT fk_e98f2859979b1ad6 FOREIGN KEY (company_id) REFERENCES public.mercenary_company(id);


--
-- Name: contract fk_e98f2859cd59f015; Type: FK CONSTRAINT; Schema: public; Owner: p1mps
--

ALTER TABLE ONLY public.contract
    ADD CONSTRAINT fk_e98f2859cd59f015 FOREIGN KEY (linked_contract_id) REFERENCES public.contract(id) ON DELETE SET NULL;


--
-- Name: contract fk_e98f2859ea4ebd8c; Type: FK CONSTRAINT; Schema: public; Owner: p1mps
--

ALTER TABLE ONLY public.contract
    ADD CONSTRAINT fk_e98f2859ea4ebd8c FOREIGN KEY (opposing_company_id) REFERENCES public.mercenary_company(id);


--
-- Name: salvaged_mech fk_f1533ac5979b1ad6; Type: FK CONSTRAINT; Schema: public; Owner: p1mps
--

ALTER TABLE ONLY public.salvaged_mech
    ADD CONSTRAINT fk_f1533ac5979b1ad6 FOREIGN KEY (company_id) REFERENCES public.mercenary_company(id);


--
-- Name: salvaged_mech fk_f1533ac59863015; Type: FK CONSTRAINT; Schema: public; Owner: p1mps
--

ALTER TABLE ONLY public.salvaged_mech
    ADD CONSTRAINT fk_f1533ac59863015 FOREIGN KEY (dropship_id) REFERENCES public.dropship(id) ON DELETE SET NULL;


--
-- PostgreSQL database dump complete
--

\unrestrict QstsbnGqyyt9IYY3gUx8PlEf8v6KhiuKcw469rQfWxHGQZt7pmR0uOJRTYy39JH

