<?php

namespace App\Tests\Unit\Service;

use App\Entity\MercenaryCompany;
use App\Entity\Pilot;
use App\Service\PilotService;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\EntityManagerInterface;
use PHPUnit\Framework\Attributes\CoversClass;
use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\TestCase;

#[CoversClass(PilotService::class)]
class PilotServiceTest extends TestCase
{
    private EntityManagerInterface $emMock;
    private PilotService $service;

    protected function setUp(): void
    {
        $this->emMock = $this->createMock(EntityManagerInterface::class);
        $this->service = new PilotService($this->emMock);
    }

    /**
     * Uses reflection to set the private $id property on a Pilot entity.
     * Pilot has no setId() because id is auto-generated by Doctrine.
     */
    private function setPilotId(Pilot $pilot, int $id): void
    {
        $reflection = new \ReflectionProperty(Pilot::class, 'id');
        $reflection->setValue($pilot, $id);
    }

    // ── getPilots ────────────────────────────────────────────────────────

    public function testGetPilotsReturnsCompanyPilotsCollection(): void
    {
        $company = new MercenaryCompany();
        $company->setName('Test Company');
        $company->setFaction('Liao');

        $pilot1 = new Pilot();
        $pilot1->setName('Ace Pilot');
        $pilot1->setIsNamed(false);
        $company->getPilots()->add($pilot1);

        $pilot2 = new Pilot();
        $pilot2->setName('Rookie');
        $pilot2->setIsNamed(false);
        $company->getPilots()->add($pilot2);

        $result = $this->service->getPilots($company);

        $this->assertInstanceOf(\Doctrine\Common\Collections\Collection::class, $result);
        $this->assertCount(2, $result);
    }

    public function testGetPilotsReturnsEmptyCollectionWhenCompanyHasNoPilots(): void
    {
        $company = new MercenaryCompany();
        $company->setName('Empty Company');
        $company->setFaction('ComStar');

        $result = $this->service->getPilots($company);

        $this->assertInstanceOf(\Doctrine\Common\Collections\Collection::class, $result);
        $this->assertCount(0, $result);
    }

    public function testGetPilotsReturnsSameCollectionAsOnCompany(): void
    {
        $company = new MercenaryCompany();
        $company->setName('Test Company');
        $company->setFaction('Word of Blake');

        $pilot = new Pilot();
        $pilot->setName('Test Pilot');
        $company->getPilots()->add($pilot);

        $result = $this->service->getPilots($company);

        $this->assertSame($company->getPilots(), $result);
    }

    // ── getXpThresholdAlerts ─────────────────────────────────────────────

    public function testGetXpThresholdAlertsReturnsEmptyArrayWhenNoPilots(): void
    {
        $emptyCollection = new ArrayCollection();
        $result = $this->service->getXpThresholdAlerts($emptyCollection);

        $this->assertIsArray($result);
        $this->assertEmpty($result);
    }

    public function testGetXpThresholdAlertsSkipsUnnamedPilots(): void
    {
        $pilot = new Pilot();
        $pilot->setName('Regular Pilot');
        $pilot->setIsNamed(false);
        $pilot->setGunnery(4);
        $pilot->setPiloting(5);
        $pilot->setXp(9999);

        $collection = new ArrayCollection([$pilot]);
        $result = $this->service->getXpThresholdAlerts($collection);

        $this->assertIsArray($result);
        $this->assertEmpty($result);
    }

    public function testGetXpThresholdAlertsReturnsAlertsForNamedPilotsNearThreshold(): void
    {
        $pilot = new Pilot();
        $this->setPilotId($pilot, 42);
        $pilot->setName('Legendary Pilot');
        $pilot->setIsNamed(true);
        $pilot->setGunnery(6);
        $pilot->setPiloting(7);
        $pilot->setXp(100);

        $collection = new ArrayCollection([$pilot]);
        $result = $this->service->getXpThresholdAlerts($collection);

        $this->assertIsArray($result);
        // The alert may or may not exist depending on XpThresholdsTable logic,
        // but the method should not throw
    }

    public function testGetXpThresholdAlertsWithMultiplePilots(): void
    {
        $namedPilot = new Pilot();
        $this->setPilotId($namedPilot, 1);
        $namedPilot->setName('Named Pilot');
        $namedPilot->setIsNamed(true);
        $namedPilot->setGunnery(4);
        $namedPilot->setPiloting(5);
        $namedPilot->setXp(0);

        $unnamedPilot = new Pilot();
        $unnamedPilot->setName('Unnamed Pilot');
        $unnamedPilot->setIsNamed(false);
        $unnamedPilot->setGunnery(10);
        $unnamedPilot->setPiloting(10);
        $unnamedPilot->setXp(9999);

        $collection = new ArrayCollection([$namedPilot, $unnamedPilot]);
        $result = $this->service->getXpThresholdAlerts($collection);

        $this->assertIsArray($result);
        // Only named pilots should be checked
    }

    public function testGetXpThresholdAlertsWithEmptyCollection(): void
    {
        $collection = new ArrayCollection([]);
        $result = $this->service->getXpThresholdAlerts($collection);

        $this->assertIsArray($result);
        $this->assertEmpty($result);
    }

    public function testGetXpThresholdAlertsSkipsPilotsWithoutId(): void
    {
        $pilot = new Pilot();
        $pilot->setName('Unnamed ID-less Pilot');
        $pilot->setIsNamed(true);
        $pilot->setGunnery(4);
        $pilot->setPiloting(5);
        $pilot->setXp(0);

        $collection = new ArrayCollection([$pilot]);
        $result = $this->service->getXpThresholdAlerts($collection);

        $this->assertIsArray($result);
        $this->assertEmpty($result);
    }

    public function testGetXpThresholdAlertsWithCheckImprovementReturningNull(): void
    {
        $pilot = new Pilot();
        $this->setPilotId($pilot, 7);
        $pilot->setName('Well-Trained Pilot');
        $pilot->setIsNamed(true);
        $pilot->setGunnery(8);
        $pilot->setPiloting(9);
        $pilot->setXp(500);

        $collection = new ArrayCollection([$pilot]);
        $result = $this->service->getXpThresholdAlerts($collection);

        $this->assertIsArray($result);
        // Result depends on XpThresholdsTable logic, but should never throw
    }

    public function testGetXpThresholdAlertsWithMixedNamedAndUnnamedPilots(): void
    {
        $namedPilot1 = new Pilot();
        $this->setPilotId($namedPilot1, 10);
        $namedPilot1->setName('Veteran Pilot');
        $namedPilot1->setIsNamed(true);
        $namedPilot1->setGunnery(5);
        $namedPilot1->setPiloting(6);
        $namedPilot1->setXp(50);

        $namedPilot2 = new Pilot();
        $this->setPilotId($namedPilot2, 11);
        $namedPilot2->setName('Rising Star');
        $namedPilot2->setIsNamed(true);
        $namedPilot2->setGunnery(3);
        $namedPilot2->setPiloting(4);
        $namedPilot2->setXp(10);

        $unnamedPilot = new Pilot();
        $unnamedPilot->setName('Rookie Pilot');
        $unnamedPilot->setIsNamed(false);
        $unnamedPilot->setGunnery(10);
        $unnamedPilot->setPiloting(10);
        $unnamedPilot->setXp(9999);

        $collection = new ArrayCollection([$namedPilot1, $namedPilot2, $unnamedPilot]);
        $result = $this->service->getXpThresholdAlerts($collection);

        $this->assertIsArray($result);
        $this->assertArrayNotHasKey(-1, $result);
    }

    public function testGetXpThresholdAlertsWithDuplicateNamedPilots(): void
    {
        $pilot1 = new Pilot();
        $this->setPilotId($pilot1, 100);
        $pilot1->setName('Duplicate Name');
        $pilot1->setIsNamed(true);
        $pilot1->setGunnery(4);
        $pilot1->setPiloting(5);
        $pilot1->setXp(0);

        $pilot2 = new Pilot();
        $this->setPilotId($pilot2, 101);
        $pilot2->setName('Duplicate Name');
        $pilot2->setIsNamed(true);
        $pilot2->setGunnery(4);
        $pilot2->setPiloting(5);
        $pilot2->setXp(0);

        $collection = new ArrayCollection([$pilot1, $pilot2]);
        $result = $this->service->getXpThresholdAlerts($collection);

        $this->assertIsArray($result);
        // Both named pilots should be checked independently
    }

    // ── createPilot ──────────────────────────────────────────────────────

    public function testCreatePilotSucceedsForUnnamedPilot(): void
    {
        $company = new MercenaryCompany();
        $company->setName('Test Company');
        $company->setFaction('Davion');

        $pilot = new Pilot();
        $pilot->setName('New Pilot');
        $pilot->setIsNamed(false);
        $pilot->setGunnery(4);
        $pilot->setPiloting(5);

        $this->emMock
            ->expects($this->once())
            ->method('persist')
            ->with($this->equalTo($pilot));
        $this->emMock
            ->expects($this->once())
            ->method('flush');

        $result = $this->service->createPilot($company, $pilot);

        $this->assertNull($result);
        $this->assertEquals($company, $pilot->getCompany());
    }

    public function testCreatePilotSucceedsForNamedPilotUnderLimit(): void
    {
        $company = new MercenaryCompany();
        $company->setName('Test Company');
        $company->setFaction('Liao');

        // Add 3 named pilots to company (under the limit of 4)
        for ($i = 0; $i < 3; $i++) {
            $namedPilot = new Pilot();
            $namedPilot->setName("Named Pilot $i");
            $namedPilot->setIsNamed(true);
            $company->getPilots()->add($namedPilot);
        }

        $newPilot = new Pilot();
        $newPilot->setName('Fourth Named');
        $newPilot->setIsNamed(true);

        $this->emMock
            ->expects($this->once())
            ->method('persist')
            ->with($this->equalTo($newPilot));
        $this->emMock
            ->expects($this->once())
            ->method('flush');

        $result = $this->service->createPilot($company, $newPilot);

        $this->assertNull($result);
        $this->assertEquals($company, $newPilot->getCompany());
    }

    public function testCreatePilotReturnsErrorWhenNamedPilotLimitExceeded(): void
    {
        $company = new MercenaryCompany();
        $company->setName('Full Company');
        $company->setFaction('Word of Blake');

        // Add 4 named pilots (at the limit)
        for ($i = 0; $i < 4; $i++) {
            $namedPilot = new Pilot();
            $namedPilot->setName("Named Pilot $i");
            $namedPilot->setIsNamed(true);
            $company->getPilots()->add($namedPilot);
        }

        $newPilot = new Pilot();
        $newPilot->setName('Fifth Named');
        $newPilot->setIsNamed(true);

        $this->emMock
            ->expects($this->never())
            ->method('persist');
        $this->emMock
            ->expects($this->never())
            ->method('flush');

        $result = $this->service->createPilot($company, $newPilot);

        $this->assertEquals('Maximum 4 named pilots allowed.', $result);
    }

    public function testCreatePilotDoesNotPersistWhenNamedLimitExceeded(): void
    {
        $company = new MercenaryCompany();
        $company->setName('Full Company');
        $company->setFaction('Covenant');

        for ($i = 0; $i < 4; $i++) {
            $namedPilot = new Pilot();
            $namedPilot->setName("Named Pilot $i");
            $namedPilot->setIsNamed(true);
            $company->getPilots()->add($namedPilot);
        }

        $newPilot = new Pilot();
        $newPilot->setName('Fifth Named');
        $newPilot->setIsNamed(true);

        $this->emMock
            ->expects($this->never())
            ->method('persist');
        $this->emMock
            ->expects($this->never())
            ->method('flush');

        $this->service->createPilot($company, $newPilot);

        // Verify company's named pilots count hasn't changed
        $this->assertEquals(4, $company->getNamedPilotsCount());
    }

    public function testCreatePilotSetsCompanyOnThePilot(): void
    {
        $company = new MercenaryCompany();
        $company->setName('Test Company');
        $company->setFaction('Free Worlds');

        $pilot = new Pilot();
        $pilot->setName('Test Pilot');
        $pilot->setIsNamed(false);

        $this->emMock
            ->expects($this->once())
            ->method('persist');
        $this->emMock
            ->expects($this->once())
            ->method('flush');

        $this->service->createPilot($company, $pilot);

        $this->assertEquals($company, $pilot->getCompany());
    }

    public function testCreatePilotWithExactlyFourNamedPilots(): void
    {
        $company = new MercenaryCompany();
        $company->setName('Test Company');
        $company->setFaction('ComGuard');

        for ($i = 0; $i < 4; $i++) {
            $namedPilot = new Pilot();
            $namedPilot->setName("Named Pilot $i");
            $namedPilot->setIsNamed(true);
            $company->getPilots()->add($namedPilot);
        }

        $newPilot = new Pilot();
        $newPilot->setName('Attempt Fifth');
        $newPilot->setIsNamed(true);

        $result = $this->service->createPilot($company, $newPilot);

        $this->assertEquals('Maximum 4 named pilots allowed.', $result);
    }

    public function testCreatePilotWithThreeNamedPilotsSucceeds(): void
    {
        $company = new MercenaryCompany();
        $company->setName('Test Company');
        $company->setFaction('Lyrans');

        for ($i = 0; $i < 3; $i++) {
            $namedPilot = new Pilot();
            $namedPilot->setName("Named Pilot $i");
            $namedPilot->setIsNamed(true);
            $company->getPilots()->add($namedPilot);
        }

        $newPilot = new Pilot();
        $newPilot->setName('Fourth Named');
        $newPilot->setIsNamed(true);

        $this->emMock
            ->expects($this->once())
            ->method('persist');
        $this->emMock
            ->expects($this->once())
            ->method('flush');

        $result = $this->service->createPilot($company, $newPilot);

        $this->assertNull($result);
    }

    /**
     * @return iterable<string, array{int}>
     */
    public static function provideNamedPilotsCounts(): iterable
    {
        return [
            'zero named' => [0],
            'one named' => [1],
            'three named' => [3],
            'four named (limit)' => [4],
            'five named (over limit)' => [5],
        ];
    }

    #[DataProvider('provideNamedPilotsCounts')]
    public function testCreatePilotWithVariousNamedCounts(int $namedCount): void
    {
        $company = new MercenaryCompany();
        $company->setName('Test Company');
        $company->setFaction('Davion');

        for ($i = 0; $i < $namedCount; $i++) {
            $namedPilot = new Pilot();
            $namedPilot->setName("Named Pilot $i");
            $namedPilot->setIsNamed(true);
            $company->getPilots()->add($namedPilot);
        }

        $newPilot = new Pilot();
        $newPilot->setName('New Pilot');
        $newPilot->setIsNamed(true);

        $result = $this->service->createPilot($company, $newPilot);

        if ($namedCount >= 4) {
            $this->assertEquals('Maximum 4 named pilots allowed.', $result);
        } else {
            $this->assertNull($result);
        }
    }

    public function testCreatePilotThrowsWhenPersistFails(): void
    {
        $company = new MercenaryCompany();
        $company->setName('Test Company');
        $company->setFaction('Davion');

        $pilot = new Pilot();
        $pilot->setName('Failing Pilot');
        $pilot->setIsNamed(false);

        $this->emMock
            ->expects($this->once())
            ->method('persist')
            ->willThrowException(new \RuntimeException('Database connection lost'));

        $this->expectException(\RuntimeException::class);
        $this->expectExceptionMessage('Database connection lost');

        $this->service->createPilot($company, $pilot);
    }

    public function testCreatePilotThrowsWhenFlushFails(): void
    {
        $company = new MercenaryCompany();
        $company->setName('Test Company');
        $company->setFaction('Liao');

        $pilot = new Pilot();
        $pilot->setName('Flush Failing Pilot');
        $pilot->setIsNamed(false);

        $this->emMock
            ->expects($this->once())
            ->method('persist');
        $this->emMock
            ->expects($this->once())
            ->method('flush')
            ->willThrowException(new \RuntimeException('Constraint violation'));

        $this->expectException(\RuntimeException::class);
        $this->expectExceptionMessage('Constraint violation');

        $this->service->createPilot($company, $pilot);
    }

    public function testCreatePilotDoesNotSetCompanyWhenNamedLimitExceeded(): void
    {
        $company = new MercenaryCompany();
        $company->setName('Full Company');
        $company->setFaction('Word of Blake');

        for ($i = 0; $i < 4; $i++) {
            $namedPilot = new Pilot();
            $namedPilot->setName("Named Pilot $i");
            $namedPilot->setIsNamed(true);
            $company->getPilots()->add($namedPilot);
        }

        $newPilot = new Pilot();
        $newPilot->setName('Fifth Named');
        $newPilot->setIsNamed(true);

        // Verify persist and flush were never called (early return path)
        $this->emMock
            ->expects($this->never())
            ->method('persist');
        $this->emMock
            ->expects($this->never())
            ->method('flush');

        $this->service->createPilot($company, $newPilot);

        // Since company is a non-nullable typed property, we verify the early-return
        // path by confirming the error message was returned and no DB operations occurred.
        // The Pilot entity does not expose setId/setCompany for testing, so we verify
        // behavior indirectly through the mocked EM expectations above.
    }

    public function testCreatePilotWithUnnamedPilotOverNamedLimitStillSucceeds(): void
    {
        $company = new MercenaryCompany();
        $company->setName('Test Company');
        $company->setFaction('ComStar');

        for ($i = 0; $i < 5; $i++) {
            $namedPilot = new Pilot();
            $namedPilot->setName("Named Pilot $i");
            $namedPilot->setIsNamed(true);
            $company->getPilots()->add($namedPilot);
        }

        $newPilot = new Pilot();
        $newPilot->setName('Unnamed Over Limit');
        $newPilot->setIsNamed(false);

        $this->emMock
            ->expects($this->once())
            ->method('persist');
        $this->emMock
            ->expects($this->once())
            ->method('flush');

        $result = $this->service->createPilot($company, $newPilot);

        $this->assertNull($result);
        $this->assertEquals($company, $newPilot->getCompany());
    }

    // ── updatePilot ──────────────────────────────────────────────────────

    public function testUpdatePilotCallsFlush(): void
    {
        $pilot = new Pilot();
        $pilot->setName('Updated Pilot');

        $this->emMock
            ->expects($this->once())
            ->method('flush');

        $this->service->updatePilot($pilot);
    }

    public function testUpdatePilotDoesNotCallPersist(): void
    {
        $pilot = new Pilot();
        $pilot->setName('Updated Pilot');

        $this->emMock
            ->expects($this->never())
            ->method('persist');
        $this->emMock
            ->expects($this->once())
            ->method('flush');

        $this->service->updatePilot($pilot);
    }

    public function testUpdatePilotDoesNotReturnAnything(): void
    {
        $pilot = new Pilot();
        $pilot->setName('Updated Pilot');

        $this->emMock
            ->expects($this->once())
            ->method('flush');

        $result = $this->service->updatePilot($pilot);

        $this->assertNull($result);
    }

    public function testUpdatePilotWithMinimalPilot(): void
    {
        $pilot = new Pilot();

        $this->emMock
            ->expects($this->once())
            ->method('flush');

        $this->service->updatePilot($pilot);
    }

    public function testUpdatePilotWithFullPilot(): void
    {
        $pilot = new Pilot();
        $this->setPilotId($pilot, 42);
        $pilot->setName('Full Pilot');
        $pilot->setIsNamed(true);
        $pilot->setGunnery(7);
        $pilot->setPiloting(8);
        $pilot->setXp(250);

        $this->emMock
            ->expects($this->once())
            ->method('flush');

        $this->service->updatePilot($pilot);
    }

    public function testUpdatePilotThrowsOnFlushError(): void
    {
        $pilot = new Pilot();
        $pilot->setName('Error Pilot');

        $this->emMock
            ->expects($this->once())
            ->method('flush')
            ->willThrowException(new \RuntimeException('Lock timeout'));

        $this->expectException(\RuntimeException::class);
        $this->expectExceptionMessage('Lock timeout');

        $this->service->updatePilot($pilot);
    }

    // ── deletePilot ──────────────────────────────────────────────────────

    public function testDeletePilotCallsRemoveAndFlush(): void
    {
        $pilot = new Pilot();
        $pilot->setName('Pilot to Delete');

        $this->emMock
            ->expects($this->once())
            ->method('remove')
            ->with($this->equalTo($pilot));
        $this->emMock
            ->expects($this->once())
            ->method('flush');

        $this->service->deletePilot($pilot);
    }

    public function testDeletePilotRemovesTheCorrectPilot(): void
    {
        $pilot = new Pilot();
        $pilot->setName('Pilot to Delete');

        $capturedPilot = null;
        $this->emMock
            ->method('remove')
            ->willReturnCallback(function ($entity) use (&$capturedPilot) {
                $capturedPilot = $entity;
            });
        $this->emMock
            ->expects($this->once())
            ->method('flush');

        $this->service->deletePilot($pilot);

        $this->assertSame($pilot, $capturedPilot);
    }

    public function testDeletePilotDoesNotReturnAnything(): void
    {
        $pilot = new Pilot();
        $pilot->setName('Pilot to Delete');

        $this->emMock
            ->expects($this->once())
            ->method('remove');
        $this->emMock
            ->expects($this->once())
            ->method('flush');

        $result = $this->service->deletePilot($pilot);

        $this->assertNull($result);
    }

    public function testDeletePilotThrowsOnFlushError(): void
    {
        $pilot = new Pilot();
        $pilot->setName('Deletion Error Pilot');

        $this->emMock
            ->expects($this->once())
            ->method('remove');
        $this->emMock
            ->expects($this->once())
            ->method('flush')
            ->willThrowException(new \RuntimeException('Foreign key constraint'));

        $this->expectException(\RuntimeException::class);
        $this->expectExceptionMessage('Foreign key constraint');

        $this->service->deletePilot($pilot);
    }

    public function testDeletePilotWithMinimalPilot(): void
    {
        $pilot = new Pilot();

        $this->emMock
            ->expects($this->once())
            ->method('remove');
        $this->emMock
            ->expects($this->once())
            ->method('flush');

        $this->service->deletePilot($pilot);
    }

    public function testDeletePilotWithNamedPilot(): void
    {
        $pilot = new Pilot();
        $pilot->setName('Legendary Ace');
        $pilot->setIsNamed(true);
        $this->setPilotId($pilot, 99);

        $capturedPilot = null;
        $this->emMock
            ->method('remove')
            ->willReturnCallback(function ($entity) use (&$capturedPilot) {
                $capturedPilot = $entity;
            });
        $this->emMock
            ->expects($this->once())
            ->method('flush');

        $this->service->deletePilot($pilot);

        $this->assertSame($pilot, $capturedPilot);
    }

    // ── getPilots — additional edge cases ─────────────────────────────────

    public function testGetPilotsWithLargeCollection(): void
    {
        $company = new MercenaryCompany();
        $company->setName('Large Company');
        $company->setFaction('Davion');

        for ($i = 0; $i < 20; $i++) {
            $pilot = new Pilot();
            $pilot->setName("Pilot $i");
            $pilot->setIsNamed($i % 4 === 0);
            $company->getPilots()->add($pilot);
        }

        $result = $this->service->getPilots($company);

        $this->assertCount(20, $result);
    }

    public function testGetPilotsWithAllNamedPilots(): void
    {
        $company = new MercenaryCompany();
        $company->setName('All Named Company');
        $company->setFaction('Liao');

        for ($i = 0; $i < 6; $i++) {
            $pilot = new Pilot();
            $pilot->setName("Named Pilot $i");
            $pilot->setIsNamed(true);
            $company->getPilots()->add($pilot);
        }

        $result = $this->service->getPilots($company);

        $this->assertCount(6, $result);
        foreach ($result as $pilot) {
            $this->assertTrue($pilot->isNamed());
        }
    }

    public function testGetPilotsWithAllUnnamedPilots(): void
    {
        $company = new MercenaryCompany();
        $company->setName('All Unnamed Company');
        $company->setFaction('ComGuard');

        for ($i = 0; $i < 10; $i++) {
            $pilot = new Pilot();
            $pilot->setName("Unnamed Pilot $i");
            $pilot->setIsNamed(false);
            $company->getPilots()->add($pilot);
        }

        $result = $this->service->getPilots($company);

        $this->assertCount(10, $result);
        foreach ($result as $pilot) {
            $this->assertFalse($pilot->isNamed());
        }
    }
}
