<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260731083825 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE dropship (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, max_capacity INT NOT NULL, company_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9170D952979B1AD6 ON dropship (company_id)');
        $this->addSql('ALTER TABLE dropship ADD CONSTRAINT FK_9170D952979B1AD6 FOREIGN KEY (company_id) REFERENCES mercenary_company (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE salvaged_mech ADD dropship_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE salvaged_mech ADD CONSTRAINT FK_F1533AC59863015 FOREIGN KEY (dropship_id) REFERENCES dropship (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_F1533AC59863015 ON salvaged_mech (dropship_id)');
        $this->addSql('ALTER INDEX idx_bcbca8949b5b7f0 RENAME TO IDX_F1533AC52576E0FD');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE dropship DROP CONSTRAINT FK_9170D952979B1AD6');
        $this->addSql('DROP TABLE dropship');
        $this->addSql('ALTER TABLE salvaged_mech DROP CONSTRAINT FK_F1533AC59863015');
        $this->addSql('DROP INDEX IDX_F1533AC59863015');
        $this->addSql('ALTER TABLE salvaged_mech DROP dropship_id');
        $this->addSql('ALTER INDEX idx_f1533ac52576e0fd RENAME TO idx_bcbca8949b5b7f0');
    }
}
