<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260624121344 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE contract (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, is_opposing BOOLEAN NOT NULL, type VARCHAR(50) NOT NULL, employer VARCHAR(255) NOT NULL, employer_affiliation VARCHAR(255) NOT NULL, scale INT NOT NULL, duration_months INT NOT NULL, base_pay_percent INT DEFAULT NULL, command_rights VARCHAR(50) NOT NULL, support_terms VARCHAR(255) NOT NULL, salvage_rights VARCHAR(255) NOT NULL, transport_terms VARCHAR(255) NOT NULL, number_of_tracks INT NOT NULL, tracks_completed INT NOT NULL, status VARCHAR(50) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, accepted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, company_id INT DEFAULT NULL, opposing_company_id INT DEFAULT NULL, linked_contract_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E98F2859979B1AD6 ON contract (company_id)');
        $this->addSql('CREATE INDEX IDX_E98F2859EA4EBD8C ON contract (opposing_company_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E98F2859CD59F015 ON contract (linked_contract_id)');
        $this->addSql('CREATE TABLE contract_log_entry (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, month INT NOT NULL, entry_type VARCHAR(50) NOT NULL, description TEXT NOT NULL, roll_result INT DEFAULT NULL, data JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, contract_id INT NOT NULL, track_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_26C82EBB2576E0FD ON contract_log_entry (contract_id)');
        $this->addSql('CREATE INDEX IDX_26C82EBB5ED23C43 ON contract_log_entry (track_id)');
        $this->addSql('CREATE TABLE mercenary_company (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, faction VARCHAR(255) NOT NULL, reputation INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_6461C2CA76ED395 ON mercenary_company (user_id)');
        $this->addSql('CREATE TABLE pilot (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, is_named BOOLEAN NOT NULL, gunnery INT NOT NULL, piloting INT NOT NULL, xp INT NOT NULL, company_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8D1E5F52979B1AD6 ON pilot (company_id)');
        $this->addSql('CREATE TABLE support_point_entry (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, amount INT NOT NULL, description VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, company_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5D56E8C3979B1AD6 ON support_point_entry (company_id)');
        $this->addSql('CREATE TABLE track_record (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, track_number INT NOT NULL, mission_type VARCHAR(255) NOT NULL, terrain VARCHAR(255) NOT NULL, command_complication TEXT DEFAULT NULL, combat_pay_tier VARCHAR(50) DEFAULT NULL, status VARCHAR(50) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, completed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, contract_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D3F65E782576E0FD ON track_record (contract_id)');
        $this->addSql('CREATE TABLE unit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, chassis VARCHAR(255) NOT NULL, tonnage INT NOT NULL, bv INT NOT NULL, unit_type VARCHAR(50) NOT NULL, damage_state VARCHAR(50) NOT NULL, is_active BOOLEAN NOT NULL, company_id INT NOT NULL, pilot_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_DCBB0C53979B1AD6 ON unit (company_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_DCBB0C53CE55439B ON unit (pilot_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, username VARCHAR(180) NOT NULL, email VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649F85E0677 ON "user" (username)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649E7927C74 ON "user" (email)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE contract ADD CONSTRAINT FK_E98F2859979B1AD6 FOREIGN KEY (company_id) REFERENCES mercenary_company (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE contract ADD CONSTRAINT FK_E98F2859EA4EBD8C FOREIGN KEY (opposing_company_id) REFERENCES mercenary_company (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE contract ADD CONSTRAINT FK_E98F2859CD59F015 FOREIGN KEY (linked_contract_id) REFERENCES contract (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE contract_log_entry ADD CONSTRAINT FK_26C82EBB2576E0FD FOREIGN KEY (contract_id) REFERENCES contract (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE contract_log_entry ADD CONSTRAINT FK_26C82EBB5ED23C43 FOREIGN KEY (track_id) REFERENCES track_record (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE mercenary_company ADD CONSTRAINT FK_6461C2CA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE pilot ADD CONSTRAINT FK_8D1E5F52979B1AD6 FOREIGN KEY (company_id) REFERENCES mercenary_company (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE support_point_entry ADD CONSTRAINT FK_5D56E8C3979B1AD6 FOREIGN KEY (company_id) REFERENCES mercenary_company (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE track_record ADD CONSTRAINT FK_D3F65E782576E0FD FOREIGN KEY (contract_id) REFERENCES contract (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE unit ADD CONSTRAINT FK_DCBB0C53979B1AD6 FOREIGN KEY (company_id) REFERENCES mercenary_company (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE unit ADD CONSTRAINT FK_DCBB0C53CE55439B FOREIGN KEY (pilot_id) REFERENCES pilot (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE contract DROP CONSTRAINT FK_E98F2859979B1AD6');
        $this->addSql('ALTER TABLE contract DROP CONSTRAINT FK_E98F2859EA4EBD8C');
        $this->addSql('ALTER TABLE contract DROP CONSTRAINT FK_E98F2859CD59F015');
        $this->addSql('ALTER TABLE contract_log_entry DROP CONSTRAINT FK_26C82EBB2576E0FD');
        $this->addSql('ALTER TABLE contract_log_entry DROP CONSTRAINT FK_26C82EBB5ED23C43');
        $this->addSql('ALTER TABLE mercenary_company DROP CONSTRAINT FK_6461C2CA76ED395');
        $this->addSql('ALTER TABLE pilot DROP CONSTRAINT FK_8D1E5F52979B1AD6');
        $this->addSql('ALTER TABLE support_point_entry DROP CONSTRAINT FK_5D56E8C3979B1AD6');
        $this->addSql('ALTER TABLE track_record DROP CONSTRAINT FK_D3F65E782576E0FD');
        $this->addSql('ALTER TABLE unit DROP CONSTRAINT FK_DCBB0C53979B1AD6');
        $this->addSql('ALTER TABLE unit DROP CONSTRAINT FK_DCBB0C53CE55439B');
        $this->addSql('DROP TABLE contract');
        $this->addSql('DROP TABLE contract_log_entry');
        $this->addSql('DROP TABLE mercenary_company');
        $this->addSql('DROP TABLE pilot');
        $this->addSql('DROP TABLE support_point_entry');
        $this->addSql('DROP TABLE track_record');
        $this->addSql('DROP TABLE unit');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
