<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260629201811 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE salvaged_mech (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, model VARCHAR(255) DEFAULT NULL, tonnage INT DEFAULT NULL, configuration TEXT DEFAULT NULL, salvaged_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, source_log_entry_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F1533AC528F5E25 ON salvaged_mech (source_log_entry_id)');
        $this->addSql('ALTER TABLE salvaged_mech ADD CONSTRAINT FK_F1533AC528F5E25 FOREIGN KEY (source_log_entry_id) REFERENCES contract_log_entry (id) NOT DEFERRABLE');
        $this->addSql('ALTER INDEX uniq_70799797a7b9b420 RENAME TO UNIQ_26C82EBBE1076051');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE salvaged_mech DROP CONSTRAINT FK_F1533AC528F5E25');
        $this->addSql('DROP TABLE salvaged_mech');
        $this->addSql('ALTER INDEX uniq_26c82ebbe1076051 RENAME TO uniq_70799797a7b9b420');
    }
}
