<?php
namespace App\DataTables;

class PlanetTable
{
    private const HINTERLANDS_PLANETS = [
        'Manaringaine',
        "Von Strang's World",
        'Ferris',
        'The Rock',
        'Nyserta',
        "Drask's Den",
        'Botany Bay',
        'Placida',
        'Paulus Prime',
        'Elissa',
        'Blackstone',
        'Sigurd',
        'Last Chance',
        'Crellacor',
        'Gotterdammerung',
        'Oberon VI',
        'Gustrell',
        'Premana',
        'Ayacucho',
        'Valloire',
        'Acrux',
        'Buena',
        'Czarvowo',
        'Rosice',
        'Sierpc',
        'Medzev',
        'Radostov',
        'Drosendo',
        'Herzberg',
        'Aristotle',
        'Eidsfoss',
        'Seginus',
        'Kochab',
        'Skye',
        'Skondia',
        'Sabik',
        'Clinton',
        'Laia',
        'Glurpid',
        'Atria',
        'Alkaid',
        'Soilihull',
        'Hesperus II',
        'Zebebelgenubi',
        'Arganda',
        'Nusakan',
        'Syrma',
        'Imbros II',
        'Caledonia',
        'Carsphairn',
        'Galatea',
        'Lyons',
        'Sarpsborg',
        'Lamon',
        'Summer',
        'Vindemiatrix',
        'Alcor',
        'Mizar',
        'Lambrecht',
        'Dyev',
        'Pik',
        'Uzhgorod',
        'Zvolen',
        'Kitzingen',
    ];

    public static function randomPlanet(): string
    {
        return self::HINTERLANDS_PLANETS[array_rand(self::HINTERLANDS_PLANETS)];
    }
}
